CREATE TABLE [dbo].[Employee]
(
	[Id] TIdentifier not null primary key identity,
	[State] TState not null,
	[IsEmployee] bit not null default(1),
	[EmployeeAccountId] TIdentifier null,
	[FileAs] TName not null,
	[AccountId] TIdentifier not null,
	[TradeMarkId] TIdentifier null,
	[PositionId] TIdentifier null,
	[ContactGroupId] TIdentifier null,
	[ContactRoleId] TIdentifier null,
	[ReportsToEmployeeId] TIdentifier null,
	[DivisionId] TIdentifier null,
	[AssignedToEmployeeId] TIdentifier null,
	[LeadSourceId] TIdentifier null,
	[Title] nvarchar(128) null,
	[Department] nvarchar(128) null,

	[FirstName] nvarchar(64) null,
	[MiddleName] nvarchar(64) null,
	[LastName] nvarchar(64) null,
	[BirthDate] date null,
	[Gender] tinyint not null default(0),

	[BusinessPhone] varchar(128) null,
	[MobilePhone] varchar(128) null,
	[HomePhone] varchar(128) null,
	[OtherPhone] varchar(128) null,
	[Fax] varchar(128) null,
	[Email] varchar(128) null,
	[OtherEmail] varchar(128) null,
	[Assistant] nvarchar(128) null,
	[AssistantPhone] varchar(128) null,
	
	[PrimaryAddressStreet] nvarchar(256) null,
	[PrimaryAddressCity] nvarchar(64) null,
	[PrimaryAddressRegion] nvarchar(64) null,
	[PrimaryAddressPostalCode] nvarchar(10) null,
	[PrimaryAddressCountry] nvarchar(64) null,

	[AlternateAddressStreet] nvarchar(256) null,
	[AlternateAddressCity] nvarchar(64) null,
	[AlternateAddressRegion] nvarchar(64) null,
	[AlternateAddressPostalCode] nvarchar(10) null,
	[AlternateAddressCountry] nvarchar(64) null,
	[UserId] TIdentifier null,
	[Comments] nvarchar(max) null, 
    [Created] datetime not null, 
    [CreatedBy] int not null, 
    [Modified] datetime not null, 
    [ModifiedBy] int not null, 
    [RowVersion] rowversion not null, 
    CONSTRAINT [FK_Employee_Account] FOREIGN KEY ([AccountId]) REFERENCES [Account]([Id]), 
    CONSTRAINT [FK_Employee_Position] FOREIGN KEY ([PositionId]) REFERENCES [Position]([Id]), 
    CONSTRAINT [FK_Employee_ReportsToEmployee] FOREIGN KEY ([ReportsToEmployeeId]) REFERENCES [Employee]([Id]), 
	CONSTRAINT [FK_Employee_AssignedToEmployee] FOREIGN KEY ([AssignedToEmployeeId]) REFERENCES [Employee]([Id]), 
    CONSTRAINT [FK_Employee_Division] FOREIGN KEY ([DivisionId]) REFERENCES [Division]([Id]), 
	CONSTRAINT [FK_Employee_LeadSource] FOREIGN KEY ([LeadSourceId]) REFERENCES [LeadSource]([Id]), 
    CONSTRAINT [FK_Employee_User] FOREIGN KEY ([UserId]) REFERENCES [User]([Id]), 
    CONSTRAINT [FK_Employee_TradeMark] FOREIGN KEY ([TradeMarkId]) REFERENCES [TradeMark]([Id]), 
    CONSTRAINT [FK_Employee_ContactGroup] FOREIGN KEY ([ContactGroupId]) REFERENCES [ContactGroup]([Id]), 
    CONSTRAINT [FK_Employee_ContactRole] FOREIGN KEY ([ContactRoleId]) REFERENCES [ContactRole]([Id]), 
    CONSTRAINT [CK_Employee_ReportsToEmployeeId] CHECK ([Id] <> [ReportsToEmployeeId]), 
    CONSTRAINT [FK_Employee_EmployeeAccountId] FOREIGN KEY ([EmployeeAccountId]) REFERENCES [Account]([Id])
)
