CREATE TABLE [dbo].[MoneyOperation]
(
	[Id] TIdentifier not null primary key identity, 
	[State] TState not null,
	[FileAs] TName not null,
	[Number] TCode not null,
	[DocumentDate] date not null,
	[OrganizationId] TIdentifier not null,
	[ParentId] TIdentifier null,
	[BankAccountId] TIdentifier NOT null,
	[MoneyOperationTypeId] TIdentifier not null,
	[MoneyOperationDirection] int not null default(1),
	[BudgetId] TIdentifier null,
	[OperatingBudgetId] TIdentifier null,
	[BudgetItemGroupId] TIdentifier null,
	[BudgetItemId] TIdentifier null,
	[PurchaseInvoiceId] TIdentifier null,
	[SalesInvoiceId] TIdentifier null,
	[AccountId] TIdentifier not null,
	[EmployeeId] TIdentifier null,
	[Subject] nvarchar(1024) null,
	[Value] [TMoney] not null,
	[VATRateId] TIdentifier null,
	[VATValue] [TMoney] not null,
    [Comments] NVARCHAR(MAX) NULL, 
    [Created] DATETIME NOT NULL, 
    [CreatedBy] INT NOT NULL, 
    [Modified] DATETIME NOT NULL, 
    [ModifiedBy] INT NOT NULL, 
    [RowVersion] rowversion NOT NULL, 
    CONSTRAINT [FK_MoneyOperation_Organization] FOREIGN KEY ([OrganizationId]) REFERENCES [Account]([Id]), 
    CONSTRAINT [FK_MoneyOperation_BankAccount] FOREIGN KEY ([BankAccountId]) REFERENCES [BankAccount]([Id]), 
    CONSTRAINT [FK_MoneyOperation_MoneyOperationType] FOREIGN KEY ([MoneyOperationTypeId]) REFERENCES [MoneyOperationType]([Id]), 
    CONSTRAINT [FK_MoneyOperation_Budget] FOREIGN KEY ([BudgetId]) REFERENCES [Budget]([Id]), 
    CONSTRAINT [FK_MoneyOperation_OperatingBudget] FOREIGN KEY ([OperatingBudgetId]) REFERENCES [OperatingBudget]([Id]), 
    CONSTRAINT [FK_MoneyOperation_BudgetItemGroup] FOREIGN KEY ([BudgetItemGroupId]) REFERENCES [BudgetItemGroup]([Id]), 
    CONSTRAINT [FK_MoneyOperation_BudgetItem] FOREIGN KEY ([BudgetItemId]) REFERENCES [BudgetItem]([Id]), 
    CONSTRAINT [FK_MoneyOperation_Account] FOREIGN KEY ([AccountId]) REFERENCES [Account]([Id]), 
    CONSTRAINT [FK_MoneyOperation_VATRate] FOREIGN KEY ([VATRateId]) REFERENCES [VATRate]([Id]), 
    CONSTRAINT [FK_MoneyOperation_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [Employee]([Id]), 
    CONSTRAINT [FK_MoneyOperation_Parent] FOREIGN KEY ([ParentId]) REFERENCES [MoneyOperation]([Id]), 
    CONSTRAINT [FK_MoneyOperation_PurchaseInvoice] FOREIGN KEY ([PurchaseInvoiceId]) REFERENCES [PurchaseInvoice]([Id]), 
    CONSTRAINT [FK_MoneyOperation_SalesInvoice] FOREIGN KEY ([SalesInvoiceId]) REFERENCES [SalesInvoice]([Id]),
)
