CREATE TABLE [dbo].[EstimatesDocument]
(
	[Id] TIdentifier not null primary key identity, 
	[State] TState not null,
	[FileAs] TName not null,
	[Number] TCode not null,
	[DocumentDate] date not null,
	[OrganizationId] TIdentifier not null,
	[ServiceRequestId] TIdentifier not null,
	[VATRateId] TIdentifier not null default(1),
	[ExtraCostRateId] TIdentifier not null default(1),
	[Commission] TPercent not null default(0),
	[Margin] TPercent not null default(0),
	[Discount] TPercent not null default(0),
    [Comments] nvarchar(max) null, 
    [Created] datetime not null, 
    [CreatedBy] int not null, 
    [Modified] datetime not null, 
    [ModifiedBy] int not null, 
    [RowVersion] rowversion not null, 
    CONSTRAINT [FK_EstimatesDocument_Organization] FOREIGN KEY ([OrganizationId]) REFERENCES [Account]([Id]), 
    CONSTRAINT [FK_EstimatesDocument_ServiceRequest] FOREIGN KEY ([ServiceRequestId]) REFERENCES [ServiceRequest]([Id]), 
    CONSTRAINT [FK_EstimatesDocument_VATRate] FOREIGN KEY ([VATRateId]) REFERENCES [VATRate]([Id]), 
    CONSTRAINT [FK_EstimatesDocument_ExtraCostRate] FOREIGN KEY ([ExtraCostRateId]) REFERENCES [ExtraCostRate]([Id]), 
)
