CREATE TABLE [dbo].[ServiceRequest]
(
	[Id] TIdentifier not null primary key identity, 
	[State] TState not null,
	[Number] TCode not null,
	[FileAs] TName not null,
	[DocumentDate] date not null default(getdate()),
	[TradeMarkId] TIdentifier null,
	[OrganizationId] TIdentifier not null,
	[AccountId] TIdentifier not null,
	[CustomerId] TIdentifier null,
	[VenueProviderId] TIdentifier null,
	[AgentId] TIdentifier null,
	[ResponsibleContactId] TIdentifier null,
	[ServiceRequestTypeId] TIdentifier not null,
	[ServiceLevelId] TIdentifier not null,
	[ReasonId] TIdentifier not null,
	[LeadSourceId] TIdentifier null,
	[ProjectId] TIdentifier not null,
	[AmountOfGuests] int null,
	[Value] money null,
	[Mileage] int null,
	[EventLocation] nvarchar(256),
	[EventMonth] date null,
	[EventDate] date null,
	[EventDuration] int not null,
    [Comments] nvarchar(max) null, 
    [Created] datetime not null, 
    [CreatedBy] int not null, 
    [Modified] datetime not null, 
    [ModifiedBy] int not null, 
    [RowVersion] rowversion not null, 
    CONSTRAINT [FK_ServiceRequest_Organization] FOREIGN KEY ([OrganizationId]) REFERENCES [Account]([Id]), 
    CONSTRAINT [FK_ServiceRequest_Account] FOREIGN KEY ([AccountId]) REFERENCES [Account]([Id]),
    CONSTRAINT [FK_ServiceRequest_ServiceRequestType] FOREIGN KEY ([ServiceRequestTypeId]) REFERENCES [ServiceRequestType]([Id]), 
    CONSTRAINT [FK_ServiceRequest_ServiceLevel] FOREIGN KEY ([ServiceLevelId]) REFERENCES [ServiceLevel]([Id]), 
    CONSTRAINT [FK_ServiceRequest_Reason] FOREIGN KEY ([ReasonId]) REFERENCES [Reason]([Id]), 
    CONSTRAINT [FK_ServiceRequest_Customer] FOREIGN KEY ([CustomerId]) REFERENCES [Account]([Id]), 
    CONSTRAINT [FK_ServiceRequest_VenueProvider] FOREIGN KEY ([VenueProviderId]) REFERENCES [Account]([Id]), 
    CONSTRAINT [FK_ServiceRequest_Agent] FOREIGN KEY ([AgentId]) REFERENCES [Account]([Id]), 
    CONSTRAINT [FK_ServiceRequest_TradeMark] FOREIGN KEY ([TradeMarkId]) REFERENCES [TradeMark]([Id]), 
    CONSTRAINT [FK_ServiceRequest_LeadSource] FOREIGN KEY ([LeadSourceId]) REFERENCES [LeadSource]([Id]), 
	CONSTRAINT [FK_ServiceRequest_Contact] FOREIGN KEY ([ResponsibleContactId]) REFERENCES [Employee]([Id]), 
    CONSTRAINT [FK_ServiceRequest_Project] FOREIGN KEY ([ProjectId]) REFERENCES [Project]([Id])
)
