//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    
    public partial class BudgetTemplateDataAdapter : XmlDataAdapterBase<BudgetTemplateView, BudgetTemplate, BudgetTemplateFilter>
    {
        private bool _initialized1;
        private int _ordinal1Id;
        private int _ordinal1State;
        private int _ordinal1FileAs;
        private int _ordinal1ServiceRequestTypeId;
        private int _ordinal1ServiceLevelId;
        private int _ordinal1AmountOfPersons;
        private int _ordinal1EventDuration;
        private int _ordinal1Comments;
        private int _ordinal1Created;
        private int _ordinal1CreatedBy;
        private int _ordinal1Modified;
        private int _ordinal1ModifiedBy;
        private int _ordinal1RowVersion;
        private void InitializeBindBrowseResultToItem(SqlDataReader reader)
        {
            if (this._initialized1) return;
            this._ordinal1Id = reader.GetOrdinal("Id");
            this._ordinal1State = reader.GetOrdinal("State");
            this._ordinal1FileAs = reader.GetOrdinal("FileAs");
            this._ordinal1ServiceRequestTypeId = reader.GetOrdinal("ServiceRequestTypeId");
            this._ordinal1ServiceLevelId = reader.GetOrdinal("ServiceLevelId");
            this._ordinal1AmountOfPersons = reader.GetOrdinal("AmountOfPersons");
            this._ordinal1EventDuration = reader.GetOrdinal("EventDuration");
            this._ordinal1Comments = reader.GetOrdinal("Comments");
            this._ordinal1Created = reader.GetOrdinal("Created");
            this._ordinal1CreatedBy = reader.GetOrdinal("CreatedBy");
            this._ordinal1Modified = reader.GetOrdinal("Modified");
            this._ordinal1ModifiedBy = reader.GetOrdinal("ModifiedBy");
            this._ordinal1RowVersion = reader.GetOrdinal("RowVersion");
            this._initialized1 = true;
        }
        protected override void BindBrowseResultToItem(BudgetTemplateView item, SqlDataReader reader)
        {
            InitializeBindBrowseResultToItem(reader);
            item.Id = reader.GetInt32(this._ordinal1Id);
            item.State = (BudgetTemplateState)reader.GetByte(this._ordinal1State);
            item.FileAs = reader.GetString(this._ordinal1FileAs);
            item.ServiceRequestTypeId = reader.GetInt32(this._ordinal1ServiceRequestTypeId);
            item.ServiceLevelId = reader.GetInt32(this._ordinal1ServiceLevelId);
            item.AmountOfPersons = reader.GetInt32(this._ordinal1AmountOfPersons);
            item.EventDuration = reader.GetInt32(this._ordinal1EventDuration);
            if(reader.IsDBNull(_ordinal1Comments)) item.Comments = null; else item.Comments = reader.GetString(this._ordinal1Comments);
            item.Created = reader.GetDateTime(this._ordinal1Created);
            item.CreatedBy = reader.GetInt32(this._ordinal1CreatedBy);
            item.Modified = reader.GetDateTime(this._ordinal1Modified);
            item.ModifiedBy = reader.GetInt32(this._ordinal1ModifiedBy);
            item.RowVersion = reader.GetSqlBinary(this._ordinal1RowVersion).Value;
        }
        private bool _initialized2;
        private int _ordinal2Id;
        private int _ordinal2State;
        private int _ordinal2FileAs;
        private int _ordinal2ServiceRequestTypeId;
        private int _ordinal2ServiceLevelId;
        private int _ordinal2AmountOfPersons;
        private int _ordinal2EventDuration;
        private void InitializeBindListResultToItem(SqlDataReader reader)
        {
            if (this._initialized2) return;
            this._ordinal2Id = reader.GetOrdinal("Id");
            this._ordinal2State = reader.GetOrdinal("State");
            this._ordinal2FileAs = reader.GetOrdinal("FileAs");
            this._ordinal2ServiceRequestTypeId = reader.GetOrdinal("ServiceRequestTypeId");
            this._ordinal2ServiceLevelId = reader.GetOrdinal("ServiceLevelId");
            this._ordinal2AmountOfPersons = reader.GetOrdinal("AmountOfPersons");
            this._ordinal2EventDuration = reader.GetOrdinal("EventDuration");
            this._initialized2 = true;
        }
        protected override void BindListResultToItem(BudgetTemplateView item, SqlDataReader reader)
        {
            InitializeBindListResultToItem(reader);
            item.Id = reader.GetInt32(this._ordinal2Id);
            item.State = (BudgetTemplateState)reader.GetByte(this._ordinal2State);
            item.FileAs = reader.GetString(this._ordinal2FileAs);
            item.ServiceRequestTypeId = reader.GetInt32(this._ordinal2ServiceRequestTypeId);
            item.ServiceLevelId = reader.GetInt32(this._ordinal2ServiceLevelId);
            item.AmountOfPersons = reader.GetInt32(this._ordinal2AmountOfPersons);
            item.EventDuration = reader.GetInt32(this._ordinal2EventDuration);
        }
    }
}
