//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    
    public partial class BudgetDataAdapter : XmlDataAdapterBase<BudgetView, Budget, BudgetFilter>
    {
        private bool _initialized1;
        private int _ordinal1Id;
        private int _ordinal1State;
        private int _ordinal1FileAs;
        private int _ordinal1Number;
        private int _ordinal1DocumentDate;
        private int _ordinal1OrganizationId;
        private int _ordinal1ServiceRequestId;
        private int _ordinal1BudgetTemplateId;
        private int _ordinal1ServiceRequestDocumentDate;
        private int _ordinal1ServiceRequestNumber;
        private int _ordinal1AccountId;
        private int _ordinal1VenueProviderId;
        private int _ordinal1ReasonId;
        private int _ordinal1ServiceRequestTypeId;
        private int _ordinal1AmountOfGuests;
        private int _ordinal1EventDate;
        private int _ordinal1EventDuration;
        private int _ordinal1TradeMarkId;
        private int _ordinal1Value;
        private int _ordinal1StandardValue;
        private int _ordinal1PlannedValue;
        private int _ordinal1ActualValue;
        private int _ordinal1Comments;
        private int _ordinal1Created;
        private int _ordinal1CreatedBy;
        private int _ordinal1Modified;
        private int _ordinal1ModifiedBy;
        private int _ordinal1RowVersion;
        private void InitializeBindBrowseResultToItem(SqlDataReader reader)
        {
            if (this._initialized1) return;
            this._ordinal1Id = reader.GetOrdinal("Id");
            this._ordinal1State = reader.GetOrdinal("State");
            this._ordinal1FileAs = reader.GetOrdinal("FileAs");
            this._ordinal1Number = reader.GetOrdinal("Number");
            this._ordinal1DocumentDate = reader.GetOrdinal("DocumentDate");
            this._ordinal1OrganizationId = reader.GetOrdinal("OrganizationId");
            this._ordinal1ServiceRequestId = reader.GetOrdinal("ServiceRequestId");
            this._ordinal1BudgetTemplateId = reader.GetOrdinal("BudgetTemplateId");
            this._ordinal1ServiceRequestDocumentDate = reader.GetOrdinal("ServiceRequestDocumentDate");
            this._ordinal1ServiceRequestNumber = reader.GetOrdinal("ServiceRequestNumber");
            this._ordinal1AccountId = reader.GetOrdinal("AccountId");
            this._ordinal1VenueProviderId = reader.GetOrdinal("VenueProviderId");
            this._ordinal1ReasonId = reader.GetOrdinal("ReasonId");
            this._ordinal1ServiceRequestTypeId = reader.GetOrdinal("ServiceRequestTypeId");
            this._ordinal1AmountOfGuests = reader.GetOrdinal("AmountOfGuests");
            this._ordinal1EventDate = reader.GetOrdinal("EventDate");
            this._ordinal1EventDuration = reader.GetOrdinal("EventDuration");
            this._ordinal1TradeMarkId = reader.GetOrdinal("TradeMarkId");
            this._ordinal1Value = reader.GetOrdinal("Value");
            this._ordinal1StandardValue = reader.GetOrdinal("StandardValue");
            this._ordinal1PlannedValue = reader.GetOrdinal("PlannedValue");
            this._ordinal1ActualValue = reader.GetOrdinal("ActualValue");
            this._ordinal1Comments = reader.GetOrdinal("Comments");
            this._ordinal1Created = reader.GetOrdinal("Created");
            this._ordinal1CreatedBy = reader.GetOrdinal("CreatedBy");
            this._ordinal1Modified = reader.GetOrdinal("Modified");
            this._ordinal1ModifiedBy = reader.GetOrdinal("ModifiedBy");
            this._ordinal1RowVersion = reader.GetOrdinal("RowVersion");
            this._initialized1 = true;
        }
        protected override void BindBrowseResultToItem(BudgetView item, SqlDataReader reader)
        {
            InitializeBindBrowseResultToItem(reader);
            item.Id = reader.GetInt32(this._ordinal1Id);
            item.State = (BudgetState)reader.GetByte(this._ordinal1State);
            item.FileAs = reader.GetString(this._ordinal1FileAs);
            item.Number = reader.GetString(this._ordinal1Number);
            item.DocumentDate = reader.GetDateTime(this._ordinal1DocumentDate);
            item.OrganizationId = reader.GetInt32(this._ordinal1OrganizationId);
            item.ServiceRequestId = reader.GetInt32(this._ordinal1ServiceRequestId);
            if(reader.IsDBNull(_ordinal1BudgetTemplateId)) item.BudgetTemplateId = null; else item.BudgetTemplateId = reader.GetInt32(this._ordinal1BudgetTemplateId);
            item.ServiceRequestDocumentDate = reader.GetDateTime(this._ordinal1ServiceRequestDocumentDate);
            item.ServiceRequestNumber = reader.GetString(this._ordinal1ServiceRequestNumber);
            item.AccountId = reader.GetInt32(this._ordinal1AccountId);
            if(reader.IsDBNull(_ordinal1VenueProviderId)) item.VenueProviderId = null; else item.VenueProviderId = reader.GetInt32(this._ordinal1VenueProviderId);
            item.ReasonId = reader.GetInt32(this._ordinal1ReasonId);
            item.ServiceRequestTypeId = reader.GetInt32(this._ordinal1ServiceRequestTypeId);
            if(reader.IsDBNull(_ordinal1AmountOfGuests)) item.AmountOfGuests = null; else item.AmountOfGuests = reader.GetInt32(this._ordinal1AmountOfGuests);
            if(reader.IsDBNull(_ordinal1EventDate)) item.EventDate = null; else item.EventDate = reader.GetDateTime(this._ordinal1EventDate);
            if(reader.IsDBNull(_ordinal1EventDuration)) item.EventDuration = null; else item.EventDuration = reader.GetInt32(this._ordinal1EventDuration);
            if(reader.IsDBNull(_ordinal1TradeMarkId)) item.TradeMarkId = null; else item.TradeMarkId = reader.GetInt32(this._ordinal1TradeMarkId);
            item.Value = reader.GetDecimal(this._ordinal1Value);
            if(reader.IsDBNull(_ordinal1StandardValue)) item.StandardValue = null; else item.StandardValue = reader.GetDecimal(this._ordinal1StandardValue);
            if(reader.IsDBNull(_ordinal1PlannedValue)) item.PlannedValue = null; else item.PlannedValue = reader.GetDecimal(this._ordinal1PlannedValue);
            if(reader.IsDBNull(_ordinal1ActualValue)) item.ActualValue = null; else item.ActualValue = reader.GetDecimal(this._ordinal1ActualValue);
            if(reader.IsDBNull(_ordinal1Comments)) item.Comments = null; else item.Comments = reader.GetString(this._ordinal1Comments);
            item.Created = reader.GetDateTime(this._ordinal1Created);
            item.CreatedBy = reader.GetInt32(this._ordinal1CreatedBy);
            item.Modified = reader.GetDateTime(this._ordinal1Modified);
            item.ModifiedBy = reader.GetInt32(this._ordinal1ModifiedBy);
            item.RowVersion = reader.GetSqlBinary(this._ordinal1RowVersion).Value;
        }
        private bool _initialized2;
        private int _ordinal2Id;
        private int _ordinal2State;
        private int _ordinal2FileAs;
        private int _ordinal2Number;
        private int _ordinal2DocumentDate;
        private int _ordinal2OrganizationId;
        private int _ordinal2ServiceRequestId;
        private int _ordinal2BudgetTemplateId;
        private int _ordinal2ServiceRequestDocumentDate;
        private int _ordinal2ServiceRequestNumber;
        private int _ordinal2AccountId;
        private int _ordinal2VenueProviderId;
        private int _ordinal2ReasonId;
        private int _ordinal2ServiceRequestTypeId;
        private int _ordinal2AmountOfGuests;
        private int _ordinal2EventDate;
        private int _ordinal2EventDuration;
        private int _ordinal2TradeMarkId;
        private int _ordinal2Value;
        private void InitializeBindListResultToItem(SqlDataReader reader)
        {
            if (this._initialized2) return;
            this._ordinal2Id = reader.GetOrdinal("Id");
            this._ordinal2State = reader.GetOrdinal("State");
            this._ordinal2FileAs = reader.GetOrdinal("FileAs");
            this._ordinal2Number = reader.GetOrdinal("Number");
            this._ordinal2DocumentDate = reader.GetOrdinal("DocumentDate");
            this._ordinal2OrganizationId = reader.GetOrdinal("OrganizationId");
            this._ordinal2ServiceRequestId = reader.GetOrdinal("ServiceRequestId");
            this._ordinal2BudgetTemplateId = reader.GetOrdinal("BudgetTemplateId");
            this._ordinal2ServiceRequestDocumentDate = reader.GetOrdinal("ServiceRequestDocumentDate");
            this._ordinal2ServiceRequestNumber = reader.GetOrdinal("ServiceRequestNumber");
            this._ordinal2AccountId = reader.GetOrdinal("AccountId");
            this._ordinal2VenueProviderId = reader.GetOrdinal("VenueProviderId");
            this._ordinal2ReasonId = reader.GetOrdinal("ReasonId");
            this._ordinal2ServiceRequestTypeId = reader.GetOrdinal("ServiceRequestTypeId");
            this._ordinal2AmountOfGuests = reader.GetOrdinal("AmountOfGuests");
            this._ordinal2EventDate = reader.GetOrdinal("EventDate");
            this._ordinal2EventDuration = reader.GetOrdinal("EventDuration");
            this._ordinal2TradeMarkId = reader.GetOrdinal("TradeMarkId");
            this._ordinal2Value = reader.GetOrdinal("Value");
            this._initialized2 = true;
        }
        protected override void BindListResultToItem(BudgetView item, SqlDataReader reader)
        {
            InitializeBindListResultToItem(reader);
            item.Id = reader.GetInt32(this._ordinal2Id);
            item.State = (BudgetState)reader.GetByte(this._ordinal2State);
            item.FileAs = reader.GetString(this._ordinal2FileAs);
            item.Number = reader.GetString(this._ordinal2Number);
            item.DocumentDate = reader.GetDateTime(this._ordinal2DocumentDate);
            item.OrganizationId = reader.GetInt32(this._ordinal2OrganizationId);
            item.ServiceRequestId = reader.GetInt32(this._ordinal2ServiceRequestId);
            if(reader.IsDBNull(_ordinal2BudgetTemplateId)) item.BudgetTemplateId = null; else item.BudgetTemplateId = reader.GetInt32(this._ordinal2BudgetTemplateId);
            item.ServiceRequestDocumentDate = reader.GetDateTime(this._ordinal2ServiceRequestDocumentDate);
            item.ServiceRequestNumber = reader.GetString(this._ordinal2ServiceRequestNumber);
            item.AccountId = reader.GetInt32(this._ordinal2AccountId);
            if(reader.IsDBNull(_ordinal2VenueProviderId)) item.VenueProviderId = null; else item.VenueProviderId = reader.GetInt32(this._ordinal2VenueProviderId);
            item.ReasonId = reader.GetInt32(this._ordinal2ReasonId);
            item.ServiceRequestTypeId = reader.GetInt32(this._ordinal2ServiceRequestTypeId);
            if(reader.IsDBNull(_ordinal2AmountOfGuests)) item.AmountOfGuests = null; else item.AmountOfGuests = reader.GetInt32(this._ordinal2AmountOfGuests);
            if(reader.IsDBNull(_ordinal2EventDate)) item.EventDate = null; else item.EventDate = reader.GetDateTime(this._ordinal2EventDate);
            if(reader.IsDBNull(_ordinal2EventDuration)) item.EventDuration = null; else item.EventDuration = reader.GetInt32(this._ordinal2EventDuration);
            if(reader.IsDBNull(_ordinal2TradeMarkId)) item.TradeMarkId = null; else item.TradeMarkId = reader.GetInt32(this._ordinal2TradeMarkId);
            item.Value = reader.GetDecimal(this._ordinal2Value);
        }
    }
}
