//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    
    public partial class DocumentEmployeeAccessRightDataAdapter : XmlDataAdapterBase<DocumentEmployeeAccessRightView, DocumentEmployeeAccessRight, DocumentEmployeeAccessRightFilter>
    {
        private bool _initialized1;
        private int _ordinal1Id;
        private int _ordinal1State;
        private int _ordinal1DocumentTypeId;
        private int _ordinal1DocumentId;
        private int _ordinal1DocumentAccessTypeId;
        private int _ordinal1EmployeeId;
        private int _ordinal1StartDate;
        private int _ordinal1EndDate;
        private int _ordinal1Created;
        private int _ordinal1CreatedBy;
        private int _ordinal1Modified;
        private int _ordinal1ModifiedBy;
        private int _ordinal1RowVersion;
        private void InitializeBindBrowseResultToItem(SqlDataReader reader)
        {
            if (this._initialized1) return;
            this._ordinal1Id = reader.GetOrdinal("Id");
            this._ordinal1State = reader.GetOrdinal("State");
            this._ordinal1DocumentTypeId = reader.GetOrdinal("DocumentTypeId");
            this._ordinal1DocumentId = reader.GetOrdinal("DocumentId");
            this._ordinal1DocumentAccessTypeId = reader.GetOrdinal("DocumentAccessTypeId");
            this._ordinal1EmployeeId = reader.GetOrdinal("EmployeeId");
            this._ordinal1StartDate = reader.GetOrdinal("StartDate");
            this._ordinal1EndDate = reader.GetOrdinal("EndDate");
            this._ordinal1Created = reader.GetOrdinal("Created");
            this._ordinal1CreatedBy = reader.GetOrdinal("CreatedBy");
            this._ordinal1Modified = reader.GetOrdinal("Modified");
            this._ordinal1ModifiedBy = reader.GetOrdinal("ModifiedBy");
            this._ordinal1RowVersion = reader.GetOrdinal("RowVersion");
            this._initialized1 = true;
        }
        protected override void BindBrowseResultToItem(DocumentEmployeeAccessRightView item, SqlDataReader reader)
        {
            InitializeBindBrowseResultToItem(reader);
            item.Id = reader.GetInt32(this._ordinal1Id);
            item.State = (DocumentEmployeeAccessRightState)reader.GetByte(this._ordinal1State);
            item.DocumentTypeId = reader.GetInt32(this._ordinal1DocumentTypeId);
            item.DocumentId = reader.GetInt32(this._ordinal1DocumentId);
            item.DocumentAccessTypeId = reader.GetInt32(this._ordinal1DocumentAccessTypeId);
            item.EmployeeId = reader.GetInt32(this._ordinal1EmployeeId);
            if(reader.IsDBNull(_ordinal1StartDate)) item.StartDate = null; else item.StartDate = reader.GetDateTime(this._ordinal1StartDate);
            if(reader.IsDBNull(_ordinal1EndDate)) item.EndDate = null; else item.EndDate = reader.GetDateTime(this._ordinal1EndDate);
            item.Created = reader.GetDateTime(this._ordinal1Created);
            item.CreatedBy = reader.GetInt32(this._ordinal1CreatedBy);
            item.Modified = reader.GetDateTime(this._ordinal1Modified);
            item.ModifiedBy = reader.GetInt32(this._ordinal1ModifiedBy);
            item.RowVersion = reader.GetSqlBinary(this._ordinal1RowVersion).Value;
        }
        private bool _initialized2;
        private int _ordinal2Id;
        private int _ordinal2State;
        private int _ordinal2DocumentTypeId;
        private int _ordinal2DocumentId;
        private int _ordinal2DocumentAccessTypeId;
        private int _ordinal2EmployeeId;
        private int _ordinal2StartDate;
        private int _ordinal2EndDate;
        private void InitializeBindListResultToItem(SqlDataReader reader)
        {
            if (this._initialized2) return;
            this._ordinal2Id = reader.GetOrdinal("Id");
            this._ordinal2State = reader.GetOrdinal("State");
            this._ordinal2DocumentTypeId = reader.GetOrdinal("DocumentTypeId");
            this._ordinal2DocumentId = reader.GetOrdinal("DocumentId");
            this._ordinal2DocumentAccessTypeId = reader.GetOrdinal("DocumentAccessTypeId");
            this._ordinal2EmployeeId = reader.GetOrdinal("EmployeeId");
            this._ordinal2StartDate = reader.GetOrdinal("StartDate");
            this._ordinal2EndDate = reader.GetOrdinal("EndDate");
            this._initialized2 = true;
        }
        protected override void BindListResultToItem(DocumentEmployeeAccessRightView item, SqlDataReader reader)
        {
            InitializeBindListResultToItem(reader);
            item.Id = reader.GetInt32(this._ordinal2Id);
            item.State = (DocumentEmployeeAccessRightState)reader.GetByte(this._ordinal2State);
            item.DocumentTypeId = reader.GetInt32(this._ordinal2DocumentTypeId);
            item.DocumentId = reader.GetInt32(this._ordinal2DocumentId);
            item.DocumentAccessTypeId = reader.GetInt32(this._ordinal2DocumentAccessTypeId);
            item.EmployeeId = reader.GetInt32(this._ordinal2EmployeeId);
            if(reader.IsDBNull(_ordinal2StartDate)) item.StartDate = null; else item.StartDate = reader.GetDateTime(this._ordinal2StartDate);
            if(reader.IsDBNull(_ordinal2EndDate)) item.EndDate = null; else item.EndDate = reader.GetDateTime(this._ordinal2EndDate);
        }
    }
}
