//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Data;
    using System.Data.SqlClient;
    
    public partial class DocumentViewEntryDataAdapter : XmlDataAdapterBase<DocumentViewEntryView, DocumentViewEntry, DocumentViewEntryFilter>
    {
        private bool _initialized1;
        private int _ordinal1Id;
        private int _ordinal1State;
        private int _ordinal1FileAs;
        private int _ordinal1ClassName;
        private int _ordinal1ViewName;
        private int _ordinal1TableName;
        private int _ordinal1SchemaName;
        private int _ordinal1ClrTypeName;
        private int _ordinal1DataAdapterTypeName;
        private int _ordinal1DataAdapterMode;
        private int _ordinal1Comments;
        private int _ordinal1Created;
        private int _ordinal1CreatedBy;
        private int _ordinal1Modified;
        private int _ordinal1ModifiedBy;
        private int _ordinal1RowVersion;
        private void InitializeBindBrowseResultToItem(SqlDataReader reader)
        {
            if (this._initialized1) return;
            this._ordinal1Id = reader.GetOrdinal("Id");
            this._ordinal1State = reader.GetOrdinal("State");
            this._ordinal1FileAs = reader.GetOrdinal("FileAs");
            this._ordinal1ClassName = reader.GetOrdinal("ClassName");
            this._ordinal1ViewName = reader.GetOrdinal("ViewName");
            this._ordinal1TableName = reader.GetOrdinal("TableName");
            this._ordinal1SchemaName = reader.GetOrdinal("SchemaName");
            this._ordinal1ClrTypeName = reader.GetOrdinal("ClrTypeName");
            this._ordinal1DataAdapterTypeName = reader.GetOrdinal("DataAdapterTypeName");
            this._ordinal1DataAdapterMode = reader.GetOrdinal("DataAdapterMode");
            this._ordinal1Comments = reader.GetOrdinal("Comments");
            this._ordinal1Created = reader.GetOrdinal("Created");
            this._ordinal1CreatedBy = reader.GetOrdinal("CreatedBy");
            this._ordinal1Modified = reader.GetOrdinal("Modified");
            this._ordinal1ModifiedBy = reader.GetOrdinal("ModifiedBy");
            this._ordinal1RowVersion = reader.GetOrdinal("RowVersion");
            this._initialized1 = true;
        }
        protected override void BindBrowseResultToItem(DocumentViewEntryView item, SqlDataReader reader)
        {
            InitializeBindBrowseResultToItem(reader);
            item.Id = reader.GetInt32(this._ordinal1Id);
            item.State = (DocumentViewEntryState)reader.GetByte(this._ordinal1State);
            item.FileAs = reader.GetString(this._ordinal1FileAs);
            if(reader.IsDBNull(_ordinal1ClassName)) item.ClassName = null; else item.ClassName = reader.GetString(this._ordinal1ClassName);
            item.ViewName = reader.GetString(this._ordinal1ViewName);
            item.TableName = reader.GetString(this._ordinal1TableName);
            item.SchemaName = reader.GetString(this._ordinal1SchemaName);
            if(reader.IsDBNull(_ordinal1ClrTypeName)) item.ClrTypeName = null; else item.ClrTypeName = reader.GetString(this._ordinal1ClrTypeName);
            if(reader.IsDBNull(_ordinal1DataAdapterTypeName)) item.DataAdapterTypeName = null; else item.DataAdapterTypeName = reader.GetString(this._ordinal1DataAdapterTypeName);
            if(reader.IsDBNull(_ordinal1DataAdapterMode)) item.DataAdapterMode = null; else item.DataAdapterMode = reader.GetString(this._ordinal1DataAdapterMode);
            if(reader.IsDBNull(_ordinal1Comments)) item.Comments = null; else item.Comments = reader.GetString(this._ordinal1Comments);
            item.Created = reader.GetDateTime(this._ordinal1Created);
            item.CreatedBy = reader.GetInt32(this._ordinal1CreatedBy);
            item.Modified = reader.GetDateTime(this._ordinal1Modified);
            item.ModifiedBy = reader.GetInt32(this._ordinal1ModifiedBy);
            item.RowVersion = reader.GetSqlBinary(this._ordinal1RowVersion).Value;
        }
        private bool _initialized2;
        private int _ordinal2Id;
        private int _ordinal2State;
        private int _ordinal2FileAs;
        private int _ordinal2ClassName;
        private int _ordinal2ViewName;
        private int _ordinal2TableName;
        private int _ordinal2SchemaName;
        private int _ordinal2ClrTypeName;
        private int _ordinal2DataAdapterTypeName;
        private int _ordinal2DataAdapterMode;
        private void InitializeBindListResultToItem(SqlDataReader reader)
        {
            if (this._initialized2) return;
            this._ordinal2Id = reader.GetOrdinal("Id");
            this._ordinal2State = reader.GetOrdinal("State");
            this._ordinal2FileAs = reader.GetOrdinal("FileAs");
            this._ordinal2ClassName = reader.GetOrdinal("ClassName");
            this._ordinal2ViewName = reader.GetOrdinal("ViewName");
            this._ordinal2TableName = reader.GetOrdinal("TableName");
            this._ordinal2SchemaName = reader.GetOrdinal("SchemaName");
            this._ordinal2ClrTypeName = reader.GetOrdinal("ClrTypeName");
            this._ordinal2DataAdapterTypeName = reader.GetOrdinal("DataAdapterTypeName");
            this._ordinal2DataAdapterMode = reader.GetOrdinal("DataAdapterMode");
            this._initialized2 = true;
        }
        protected override void BindListResultToItem(DocumentViewEntryView item, SqlDataReader reader)
        {
            InitializeBindListResultToItem(reader);
            item.Id = reader.GetInt32(this._ordinal2Id);
            item.State = (DocumentViewEntryState)reader.GetByte(this._ordinal2State);
            item.FileAs = reader.GetString(this._ordinal2FileAs);
            if(reader.IsDBNull(_ordinal2ClassName)) item.ClassName = null; else item.ClassName = reader.GetString(this._ordinal2ClassName);
            item.ViewName = reader.GetString(this._ordinal2ViewName);
            item.TableName = reader.GetString(this._ordinal2TableName);
            item.SchemaName = reader.GetString(this._ordinal2SchemaName);
            if(reader.IsDBNull(_ordinal2ClrTypeName)) item.ClrTypeName = null; else item.ClrTypeName = reader.GetString(this._ordinal2ClrTypeName);
            if(reader.IsDBNull(_ordinal2DataAdapterTypeName)) item.DataAdapterTypeName = null; else item.DataAdapterTypeName = reader.GetString(this._ordinal2DataAdapterTypeName);
            if(reader.IsDBNull(_ordinal2DataAdapterMode)) item.DataAdapterMode = null; else item.DataAdapterMode = reader.GetString(this._ordinal2DataAdapterMode);
        }
    }
}
