//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum CalculationStatementState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Draft = 1,
        [XmlEnum("2")]
        Approved = 2,
        [XmlEnum("3")]
        Submitted = 3,
    }
    public partial class CalculationStatement : NumberedDataItem
    {
        public const string DataItemClassName = "CalculationStatement";
        public const string ServiceRequestIdProperty = "ServiceRequestId";
        public const string BudgetIdProperty = "BudgetId";
        public const string CalculationStageProperty = "CalculationStage";
        public const string IncomeBudgetItemIdProperty = "IncomeBudgetItemId";
        public const string ExpenseBudgetItemIdProperty = "ExpenseBudgetItemId";
        public const string DependsOnAmountOfPersonsProperty = "DependsOnAmountOfPersons";
        public const string AmountOnlyProperty = "AmountOnly";
        public const string VATRateIdProperty = "VATRateId";
        public const string MarginProperty = "Margin";
        public const string DiscountProperty = "Discount";
        public const string ResponsibleEmployeeIdProperty = "ResponsibleEmployeeId";
        private int _ServiceRequestIdField;
        private int _BudgetIdField;
        private int _CalculationStageField;
        private System.Nullable<int> _IncomeBudgetItemIdField;
        private System.Nullable<int> _ExpenseBudgetItemIdField;
        private bool _DependsOnAmountOfPersonsField;
        private bool _AmountOnlyField;
        private int _VATRateIdField;
        private decimal _MarginField;
        private decimal _DiscountField;
        private System.Nullable<int> _ResponsibleEmployeeIdField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public CalculationStatementState State
        {
            get
            {
                return (CalculationStatementState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="ServiceRequestId", IsNullable=false)]
        [XmlAttribute()]
        public int ServiceRequestId
        {
            get
            {
                return this._ServiceRequestIdField;
            }
            set
            {
                this._ServiceRequestIdField = value;
                InvokePropertyChanged("ServiceRequestId");
            }
        }
        [Column(Name="BudgetId", IsNullable=false)]
        [XmlAttribute()]
        public int BudgetId
        {
            get
            {
                return this._BudgetIdField;
            }
            set
            {
                this._BudgetIdField = value;
                InvokePropertyChanged("BudgetId");
            }
        }
        [Column(Name="CalculationStage", IsNullable=false)]
        [XmlAttribute()]
        public int CalculationStage
        {
            get
            {
                return this._CalculationStageField;
            }
            set
            {
                this._CalculationStageField = value;
                InvokePropertyChanged("CalculationStage");
            }
        }
        [Column(Name="IncomeBudgetItemId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> IncomeBudgetItemId
        {
            get
            {
                return this._IncomeBudgetItemIdField;
            }
            set
            {
                this._IncomeBudgetItemIdField = value;
                InvokePropertyChanged("IncomeBudgetItemId");
            }
        }
        [Column(Name="ExpenseBudgetItemId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> ExpenseBudgetItemId
        {
            get
            {
                return this._ExpenseBudgetItemIdField;
            }
            set
            {
                this._ExpenseBudgetItemIdField = value;
                InvokePropertyChanged("ExpenseBudgetItemId");
            }
        }
        [Column(Name="DependsOnAmountOfPersons", IsNullable=false)]
        [XmlAttribute()]
        public bool DependsOnAmountOfPersons
        {
            get
            {
                return this._DependsOnAmountOfPersonsField;
            }
            set
            {
                this._DependsOnAmountOfPersonsField = value;
                InvokePropertyChanged("DependsOnAmountOfPersons");
            }
        }
        [Column(Name="AmountOnly", IsNullable=false)]
        [XmlAttribute()]
        public bool AmountOnly
        {
            get
            {
                return this._AmountOnlyField;
            }
            set
            {
                this._AmountOnlyField = value;
                InvokePropertyChanged("AmountOnly");
            }
        }
        [Column(Name="VATRateId", IsNullable=false)]
        [XmlAttribute()]
        public int VATRateId
        {
            get
            {
                return this._VATRateIdField;
            }
            set
            {
                this._VATRateIdField = value;
                InvokePropertyChanged("VATRateId");
            }
        }
        [Column(Name="Margin", IsNullable=false)]
        [XmlAttribute()]
        public decimal Margin
        {
            get
            {
                return this._MarginField;
            }
            set
            {
                this._MarginField = value;
                InvokePropertyChanged("Margin");
            }
        }
        [Column(Name="Discount", IsNullable=false)]
        [XmlAttribute()]
        public decimal Discount
        {
            get
            {
                return this._DiscountField;
            }
            set
            {
                this._DiscountField = value;
                InvokePropertyChanged("Discount");
            }
        }
        [Column(Name="ResponsibleEmployeeId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> ResponsibleEmployeeId
        {
            get
            {
                return this._ResponsibleEmployeeIdField;
            }
            set
            {
                this._ResponsibleEmployeeIdField = value;
                InvokePropertyChanged("ResponsibleEmployeeId");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
