CREATE TABLE [dbo].[PurchaseInvoice]
(
	[Id] TIdentifier not null primary key identity, 
	[State] TState not null,
	[FileAs] TName not null,
	[Number] TCode not null,
	[DocumentDate] date not null,
	[DueDate] date null,
	[OrganizationId] TIdentifier not null,
	[AccountId] TIdentifier not null,
	[BudgetId] TIdentifier null,
	[OperatingBudgetId] TIdentifier null,
	[BudgetItemGroupId] TIdentifier not null,
	[BudgetItemId] TIdentifier null,
	[ResponsibleEmployeeId] TIdentifier NOT null,
	[Subject] nvarchar(1024) null,
	[IsCash] bit not null,
	[Value] TMoney not null,
	[VATRateId] TIdentifier null,
	[VATValue] TMoney not null,
    [Comments] nvarchar(max) null, 
    [Created] datetime not null, 
    [CreatedBy] int not null, 
    [Modified] datetime not null, 
    [ModifiedBy] int not null, 
    [RowVersion] rowversion not null, 
    CONSTRAINT [FK_PurchaseInvoice_Organization] FOREIGN KEY ([OrganizationId]) REFERENCES [Account]([Id]), 
    CONSTRAINT [FK_PurchaseInvoice_Account] FOREIGN KEY ([AccountId]) REFERENCES [Account]([Id]), 
	CONSTRAINT [FK_PurchaseInvoice_BudgetItemGroup] FOREIGN KEY ([BudgetItemGroupId]) REFERENCES [BudgetItemGroup]([Id]), 
	CONSTRAINT [FK_PurchaseInvoice_BudgetItem] FOREIGN KEY ([BudgetItemId]) REFERENCES [BudgetItem]([Id]), 
    CONSTRAINT [FK_PurchaseInvoice_ResponsibleEmployee] FOREIGN KEY ([ResponsibleEmployeeId]) REFERENCES [Employee]([Id]), 
    CONSTRAINT [FK_PurchaseInvoice_Budget] FOREIGN KEY ([BudgetId]) REFERENCES [Budget]([Id]), 
    CONSTRAINT [FK_PurchaseInvoice_VATRate] FOREIGN KEY ([VATRateId]) REFERENCES [VATRate]([Id]), 
    CONSTRAINT [FK_PurchaseInvoice_OperatingBudget] FOREIGN KEY ([OperatingBudgetId]) REFERENCES [OperatingBudget]([Id])
)
