//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum AccountEventTemplateState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
        [XmlEnum("2")]
        Inactive = 2,
    }
    public partial class AccountEventTemplate : DataItem
    {
        public const string DataItemClassName = "AccountEventTemplate";
        public const string AccountEventTypeIdProperty = "AccountEventTypeId";
        private int _AccountEventTypeIdField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public AccountEventTemplateState State
        {
            get
            {
                return (AccountEventTemplateState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="AccountEventTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int AccountEventTypeId
        {
            get
            {
                return this._AccountEventTypeIdField;
            }
            set
            {
                this._AccountEventTypeIdField = value;
                InvokePropertyChanged("AccountEventTypeId");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
