//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    
    public partial class AccountByMarketingProgramView : DataItemView
    {
        public const string DataItemClassName = "Account";
        private string _FullNameField;
        private System.Nullable<int> _MemberOfAccountIdField;
        private System.Nullable<int> _TradeMarkIdField;
        private int _AccountTypeIdField;
        private System.Nullable<int> _AccountGroupIdField;
        private System.Nullable<int> _IndustryIdField;
        private System.Nullable<int> _RegionIdField;
        private System.Nullable<int> _EmployeesField;
        private System.Nullable<decimal> _AnnualRevenueField;
        private System.Nullable<int> _ManagingOrganizationIdField;
        private System.Nullable<int> _AssignedToEmployeeIdField;
        private System.Nullable<int> _AssistantEmployeeIdField;
        private System.Nullable<int> _BudgetItemIdField;
        private System.Nullable<int> _ExecutiveIdField;
        private System.Nullable<int> _AccountantIdField;
        private string _PhoneField;
        private string _OtherPhoneField;
        private string _FaxField;
        private string _EmailField;
        private string _OtherEmailField;
        private string _WebSiteField;
        private string _BillingAddressStreetField;
        private string _BillingAddressCityField;
        private string _BillingAddressRegionField;
        private string _BillingAddressPostalCodeField;
        private string _BillingAddressCountryField;
        private string _ShippingAddressStreetField;
        private string _ShippingAddressCityField;
        private string _ShippingAddressRegionField;
        private string _ShippingAddressPostalCodeField;
        private string _ShippingAddressCountryField;
        private int _MarketingProgramTypeIdField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        public AccountState State
        {
            get
            {
                return (AccountState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        public string FullName
        {
            get
            {
                return this._FullNameField;
            }
            set
            {
                this._FullNameField = value;
            }
        }
        public System.Nullable<int> MemberOfAccountId
        {
            get
            {
                return this._MemberOfAccountIdField;
            }
            set
            {
                this._MemberOfAccountIdField = value;
            }
        }
        public System.Nullable<int> TradeMarkId
        {
            get
            {
                return this._TradeMarkIdField;
            }
            set
            {
                this._TradeMarkIdField = value;
            }
        }
        public int AccountTypeId
        {
            get
            {
                return this._AccountTypeIdField;
            }
            set
            {
                this._AccountTypeIdField = value;
            }
        }
        public System.Nullable<int> AccountGroupId
        {
            get
            {
                return this._AccountGroupIdField;
            }
            set
            {
                this._AccountGroupIdField = value;
            }
        }
        public System.Nullable<int> IndustryId
        {
            get
            {
                return this._IndustryIdField;
            }
            set
            {
                this._IndustryIdField = value;
            }
        }
        public System.Nullable<int> RegionId
        {
            get
            {
                return this._RegionIdField;
            }
            set
            {
                this._RegionIdField = value;
            }
        }
        public System.Nullable<int> Employees
        {
            get
            {
                return this._EmployeesField;
            }
            set
            {
                this._EmployeesField = value;
            }
        }
        public System.Nullable<decimal> AnnualRevenue
        {
            get
            {
                return this._AnnualRevenueField;
            }
            set
            {
                this._AnnualRevenueField = value;
            }
        }
        public System.Nullable<int> ManagingOrganizationId
        {
            get
            {
                return this._ManagingOrganizationIdField;
            }
            set
            {
                this._ManagingOrganizationIdField = value;
            }
        }
        public System.Nullable<int> AssignedToEmployeeId
        {
            get
            {
                return this._AssignedToEmployeeIdField;
            }
            set
            {
                this._AssignedToEmployeeIdField = value;
            }
        }
        public System.Nullable<int> AssistantEmployeeId
        {
            get
            {
                return this._AssistantEmployeeIdField;
            }
            set
            {
                this._AssistantEmployeeIdField = value;
            }
        }
        public System.Nullable<int> BudgetItemId
        {
            get
            {
                return this._BudgetItemIdField;
            }
            set
            {
                this._BudgetItemIdField = value;
            }
        }
        public System.Nullable<int> ExecutiveId
        {
            get
            {
                return this._ExecutiveIdField;
            }
            set
            {
                this._ExecutiveIdField = value;
            }
        }
        public System.Nullable<int> AccountantId
        {
            get
            {
                return this._AccountantIdField;
            }
            set
            {
                this._AccountantIdField = value;
            }
        }
        public string Phone
        {
            get
            {
                return this._PhoneField;
            }
            set
            {
                this._PhoneField = value;
            }
        }
        public string OtherPhone
        {
            get
            {
                return this._OtherPhoneField;
            }
            set
            {
                this._OtherPhoneField = value;
            }
        }
        public string Fax
        {
            get
            {
                return this._FaxField;
            }
            set
            {
                this._FaxField = value;
            }
        }
        public string Email
        {
            get
            {
                return this._EmailField;
            }
            set
            {
                this._EmailField = value;
            }
        }
        public string OtherEmail
        {
            get
            {
                return this._OtherEmailField;
            }
            set
            {
                this._OtherEmailField = value;
            }
        }
        public string WebSite
        {
            get
            {
                return this._WebSiteField;
            }
            set
            {
                this._WebSiteField = value;
            }
        }
        public string BillingAddressStreet
        {
            get
            {
                return this._BillingAddressStreetField;
            }
            set
            {
                this._BillingAddressStreetField = value;
            }
        }
        public string BillingAddressCity
        {
            get
            {
                return this._BillingAddressCityField;
            }
            set
            {
                this._BillingAddressCityField = value;
            }
        }
        public string BillingAddressRegion
        {
            get
            {
                return this._BillingAddressRegionField;
            }
            set
            {
                this._BillingAddressRegionField = value;
            }
        }
        public string BillingAddressPostalCode
        {
            get
            {
                return this._BillingAddressPostalCodeField;
            }
            set
            {
                this._BillingAddressPostalCodeField = value;
            }
        }
        public string BillingAddressCountry
        {
            get
            {
                return this._BillingAddressCountryField;
            }
            set
            {
                this._BillingAddressCountryField = value;
            }
        }
        public string ShippingAddressStreet
        {
            get
            {
                return this._ShippingAddressStreetField;
            }
            set
            {
                this._ShippingAddressStreetField = value;
            }
        }
        public string ShippingAddressCity
        {
            get
            {
                return this._ShippingAddressCityField;
            }
            set
            {
                this._ShippingAddressCityField = value;
            }
        }
        public string ShippingAddressRegion
        {
            get
            {
                return this._ShippingAddressRegionField;
            }
            set
            {
                this._ShippingAddressRegionField = value;
            }
        }
        public string ShippingAddressPostalCode
        {
            get
            {
                return this._ShippingAddressPostalCodeField;
            }
            set
            {
                this._ShippingAddressPostalCodeField = value;
            }
        }
        public string ShippingAddressCountry
        {
            get
            {
                return this._ShippingAddressCountryField;
            }
            set
            {
                this._ShippingAddressCountryField = value;
            }
        }
        public int MarketingProgramTypeId
        {
            get
            {
                return this._MarketingProgramTypeIdField;
            }
            set
            {
                this._MarketingProgramTypeIdField = value;
            }
        }
    }
}
