//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class BankAccountView : DataItemView
    {
        public const string DataItemClassName = "BankAccount";
        private int _AccountIdField;
        private bool _CashAccountField;
        private string _BankField;
        private string _AddressField;
        private string _AccountField;
        private string _SWIFTField;
        private string _ABAField;
        private string _BICField;
        private string _IBANField;
        private string _IntermediaryBankField;
        private string _IntermediaryAddressField;
        private string _IntermediaryAccountField;
        private string _IntermediarySWIFTField;
        private string _IntermediaryABAField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public BankAccountState State
        {
            get
            {
                return (BankAccountState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public int AccountId
        {
            get
            {
                return this._AccountIdField;
            }
            set
            {
                this._AccountIdField = value;
            }
        }
        [XmlAttribute()]
        public bool CashAccount
        {
            get
            {
                return this._CashAccountField;
            }
            set
            {
                this._CashAccountField = value;
            }
        }
        [XmlAttribute()]
        public string Bank
        {
            get
            {
                return this._BankField;
            }
            set
            {
                this._BankField = value;
            }
        }
        [XmlAttribute()]
        public string Address
        {
            get
            {
                return this._AddressField;
            }
            set
            {
                this._AddressField = value;
            }
        }
        [XmlAttribute()]
        public string Account
        {
            get
            {
                return this._AccountField;
            }
            set
            {
                this._AccountField = value;
            }
        }
        [XmlAttribute()]
        public string SWIFT
        {
            get
            {
                return this._SWIFTField;
            }
            set
            {
                this._SWIFTField = value;
            }
        }
        [XmlAttribute()]
        public string ABA
        {
            get
            {
                return this._ABAField;
            }
            set
            {
                this._ABAField = value;
            }
        }
        [XmlAttribute()]
        public string BIC
        {
            get
            {
                return this._BICField;
            }
            set
            {
                this._BICField = value;
            }
        }
        [XmlAttribute()]
        public string IBAN
        {
            get
            {
                return this._IBANField;
            }
            set
            {
                this._IBANField = value;
            }
        }
        [XmlAttribute()]
        public string IntermediaryBank
        {
            get
            {
                return this._IntermediaryBankField;
            }
            set
            {
                this._IntermediaryBankField = value;
            }
        }
        [XmlAttribute()]
        public string IntermediaryAddress
        {
            get
            {
                return this._IntermediaryAddressField;
            }
            set
            {
                this._IntermediaryAddressField = value;
            }
        }
        [XmlAttribute()]
        public string IntermediaryAccount
        {
            get
            {
                return this._IntermediaryAccountField;
            }
            set
            {
                this._IntermediaryAccountField = value;
            }
        }
        [XmlAttribute()]
        public string IntermediarySWIFT
        {
            get
            {
                return this._IntermediarySWIFTField;
            }
            set
            {
                this._IntermediarySWIFTField = value;
            }
        }
        [XmlAttribute()]
        public string IntermediaryABA
        {
            get
            {
                return this._IntermediaryABAField;
            }
            set
            {
                this._IntermediaryABAField = value;
            }
        }
    }
}
