//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class BudgetItemGroupView : DataItemView
    {
        public const string DataItemClassName = "BudgetItemGroup";
        private string _CodeField;
        private int _BudgetItemGroupTypeField;
        private bool _IsExpenseGroupField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public BudgetItemGroupState State
        {
            get
            {
                return (BudgetItemGroupState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public string Code
        {
            get
            {
                return this._CodeField;
            }
            set
            {
                this._CodeField = value;
            }
        }
        [XmlAttribute()]
        public int BudgetItemGroupType
        {
            get
            {
                return this._BudgetItemGroupTypeField;
            }
            set
            {
                this._BudgetItemGroupTypeField = value;
            }
        }
        [XmlAttribute()]
        public bool IsExpenseGroup
        {
            get
            {
                return this._IsExpenseGroupField;
            }
            set
            {
                this._IsExpenseGroupField = value;
            }
        }
    }
}
