//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum BudgetState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        StandardApproved = 1,
        [XmlEnum("2")]
        PlannedApproved = 2,
        [XmlEnum("3")]
        ActualApproved = 3,
    }
    public partial class Budget : NumberedDataItem
    {
        public const string DataItemClassName = "Budget";
        public const string ServiceRequestIdProperty = "ServiceRequestId";
        public const string BudgetTemplateIdProperty = "BudgetTemplateId";
        public const string AmountOfGuestsProperty = "AmountOfGuests";
        public const string EventDurationProperty = "EventDuration";
        public const string ValueProperty = "Value";
        private int _ServiceRequestIdField;
        private System.Nullable<int> _BudgetTemplateIdField;
        private System.Nullable<int> _AmountOfGuestsField;
        private System.Nullable<int> _EventDurationField;
        private decimal _ValueField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public BudgetState State
        {
            get
            {
                return (BudgetState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="ServiceRequestId", IsNullable=false)]
        [XmlAttribute()]
        public int ServiceRequestId
        {
            get
            {
                return this._ServiceRequestIdField;
            }
            set
            {
                this._ServiceRequestIdField = value;
                InvokePropertyChanged("ServiceRequestId");
            }
        }
        [Column(Name="BudgetTemplateId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> BudgetTemplateId
        {
            get
            {
                return this._BudgetTemplateIdField;
            }
            set
            {
                this._BudgetTemplateIdField = value;
                InvokePropertyChanged("BudgetTemplateId");
            }
        }
        [Column(Name="AmountOfGuests", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> AmountOfGuests
        {
            get
            {
                return this._AmountOfGuestsField;
            }
            set
            {
                this._AmountOfGuestsField = value;
                InvokePropertyChanged("AmountOfGuests");
            }
        }
        [Column(Name="EventDuration", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> EventDuration
        {
            get
            {
                return this._EventDurationField;
            }
            set
            {
                this._EventDurationField = value;
                InvokePropertyChanged("EventDuration");
            }
        }
        [Column(Name="Value", IsNullable=false)]
        [XmlAttribute()]
        public decimal Value
        {
            get
            {
                return this._ValueField;
            }
            set
            {
                this._ValueField = value;
                InvokePropertyChanged("Value");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
