//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum BudgetItemLinkState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
    }
    public partial class BudgetItemLink : DataItem
    {
        public const string DataItemClassName = "BudgetItemLink";
        public const string IncomeBudgetItemIdProperty = "IncomeBudgetItemId";
        public const string ExpenseBudgetItemIdProperty = "ExpenseBudgetItemId";
        private int _IncomeBudgetItemIdField;
        private int _ExpenseBudgetItemIdField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public BudgetItemLinkState State
        {
            get
            {
                return (BudgetItemLinkState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="IncomeBudgetItemId", IsNullable=false)]
        [XmlAttribute()]
        public int IncomeBudgetItemId
        {
            get
            {
                return this._IncomeBudgetItemIdField;
            }
            set
            {
                this._IncomeBudgetItemIdField = value;
                InvokePropertyChanged("IncomeBudgetItemId");
            }
        }
        [Column(Name="ExpenseBudgetItemId", IsNullable=false)]
        [XmlAttribute()]
        public int ExpenseBudgetItemId
        {
            get
            {
                return this._ExpenseBudgetItemIdField;
            }
            set
            {
                this._ExpenseBudgetItemIdField = value;
                InvokePropertyChanged("ExpenseBudgetItemId");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
