//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class BudgetTemplateView : DataItemView
    {
        public const string DataItemClassName = "BudgetTemplate";
        private int _ServiceRequestTypeIdField;
        private int _ServiceLevelIdField;
        private int _AmountOfPersonsField;
        private int _EventDurationField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public BudgetTemplateState State
        {
            get
            {
                return (BudgetTemplateState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public int ServiceRequestTypeId
        {
            get
            {
                return this._ServiceRequestTypeIdField;
            }
            set
            {
                this._ServiceRequestTypeIdField = value;
            }
        }
        [XmlAttribute()]
        public int ServiceLevelId
        {
            get
            {
                return this._ServiceLevelIdField;
            }
            set
            {
                this._ServiceLevelIdField = value;
            }
        }
        [XmlAttribute()]
        public int AmountOfPersons
        {
            get
            {
                return this._AmountOfPersonsField;
            }
            set
            {
                this._AmountOfPersonsField = value;
            }
        }
        [XmlAttribute()]
        public int EventDuration
        {
            get
            {
                return this._EventDurationField;
            }
            set
            {
                this._EventDurationField = value;
            }
        }
    }
}
