//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum BudgetTemplateState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
        [XmlEnum("2")]
        Inactive = 2,
    }
    public partial class BudgetTemplate : DataItem
    {
        public const string DataItemClassName = "BudgetTemplate";
        public const string ServiceRequestTypeIdProperty = "ServiceRequestTypeId";
        public const string ServiceLevelIdProperty = "ServiceLevelId";
        public const string AmountOfPersonsProperty = "AmountOfPersons";
        public const string EventDurationProperty = "EventDuration";
        private int _ServiceRequestTypeIdField;
        private int _ServiceLevelIdField;
        private int _AmountOfPersonsField;
        private int _EventDurationField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public BudgetTemplateState State
        {
            get
            {
                return (BudgetTemplateState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="ServiceRequestTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int ServiceRequestTypeId
        {
            get
            {
                return this._ServiceRequestTypeIdField;
            }
            set
            {
                this._ServiceRequestTypeIdField = value;
                InvokePropertyChanged("ServiceRequestTypeId");
            }
        }
        [Column(Name="ServiceLevelId", IsNullable=false)]
        [XmlAttribute()]
        public int ServiceLevelId
        {
            get
            {
                return this._ServiceLevelIdField;
            }
            set
            {
                this._ServiceLevelIdField = value;
                InvokePropertyChanged("ServiceLevelId");
            }
        }
        [Column(Name="AmountOfPersons", IsNullable=false)]
        [XmlAttribute()]
        public int AmountOfPersons
        {
            get
            {
                return this._AmountOfPersonsField;
            }
            set
            {
                this._AmountOfPersonsField = value;
                InvokePropertyChanged("AmountOfPersons");
            }
        }
        [Column(Name="EventDuration", IsNullable=false)]
        [XmlAttribute()]
        public int EventDuration
        {
            get
            {
                return this._EventDurationField;
            }
            set
            {
                this._EventDurationField = value;
                InvokePropertyChanged("EventDuration");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
