//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum BudgetItemState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
        [XmlEnum("2")]
        Inactive = 2,
    }
    public partial class BudgetItem : DataItem
    {
        public const string DataItemClassName = "BudgetItem";
        public const string CodeProperty = "Code";
        public const string BudgetItemGroupIdProperty = "BudgetItemGroupId";
        public const string BudgetItemTypeProperty = "BudgetItemType";
        private string _CodeField;
        private int _BudgetItemGroupIdField;
        private int _BudgetItemTypeField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public BudgetItemState State
        {
            get
            {
                return (BudgetItemState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="Code", IsNullable=false, MaximumLength=32)]
        [XmlAttribute()]
        public string Code
        {
            get
            {
                return this._CodeField;
            }
            set
            {
                this._CodeField = value;
                InvokePropertyChanged("Code");
            }
        }
        [Column(Name="BudgetItemGroupId", IsNullable=false)]
        [XmlAttribute()]
        public int BudgetItemGroupId
        {
            get
            {
                return this._BudgetItemGroupIdField;
            }
            set
            {
                this._BudgetItemGroupIdField = value;
                InvokePropertyChanged("BudgetItemGroupId");
            }
        }
        [Column(Name="BudgetItemType", IsNullable=false)]
        [XmlAttribute()]
        public int BudgetItemType
        {
            get
            {
                return this._BudgetItemTypeField;
            }
            set
            {
                this._BudgetItemTypeField = value;
                InvokePropertyChanged("BudgetItemType");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
