//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class BudgetView : NumberedDataItemView
    {
        public const string DataItemClassName = "Budget";
        private int _ServiceRequestIdField;
        private System.Nullable<int> _BudgetTemplateIdField;
        private System.DateTime _ServiceRequestDocumentDateField;
        private string _ServiceRequestNumberField;
        private int _AccountIdField;
        private System.Nullable<int> _VenueProviderIdField;
        private int _ReasonIdField;
        private int _ServiceRequestTypeIdField;
        private System.Nullable<int> _AmountOfGuestsField;
        private System.Nullable<System.DateTime> _EventDateField;
        private System.Nullable<int> _EventDurationField;
        private System.Nullable<int> _TradeMarkIdField;
        private decimal _ValueField;
        private System.Nullable<decimal> _StandardValueField;
        private System.Nullable<decimal> _PlannedValueField;
        private System.Nullable<decimal> _ActualValueField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public BudgetState State
        {
            get
            {
                return (BudgetState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public int ServiceRequestId
        {
            get
            {
                return this._ServiceRequestIdField;
            }
            set
            {
                this._ServiceRequestIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> BudgetTemplateId
        {
            get
            {
                return this._BudgetTemplateIdField;
            }
            set
            {
                this._BudgetTemplateIdField = value;
            }
        }
        [XmlAttribute()]
        public System.DateTime ServiceRequestDocumentDate
        {
            get
            {
                return this._ServiceRequestDocumentDateField;
            }
            set
            {
                this._ServiceRequestDocumentDateField = value;
            }
        }
        [XmlAttribute()]
        public string ServiceRequestNumber
        {
            get
            {
                return this._ServiceRequestNumberField;
            }
            set
            {
                this._ServiceRequestNumberField = value;
            }
        }
        [XmlAttribute()]
        public int AccountId
        {
            get
            {
                return this._AccountIdField;
            }
            set
            {
                this._AccountIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> VenueProviderId
        {
            get
            {
                return this._VenueProviderIdField;
            }
            set
            {
                this._VenueProviderIdField = value;
            }
        }
        [XmlAttribute()]
        public int ReasonId
        {
            get
            {
                return this._ReasonIdField;
            }
            set
            {
                this._ReasonIdField = value;
            }
        }
        [XmlAttribute()]
        public int ServiceRequestTypeId
        {
            get
            {
                return this._ServiceRequestTypeIdField;
            }
            set
            {
                this._ServiceRequestTypeIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> AmountOfGuests
        {
            get
            {
                return this._AmountOfGuestsField;
            }
            set
            {
                this._AmountOfGuestsField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<System.DateTime> EventDate
        {
            get
            {
                return this._EventDateField;
            }
            set
            {
                this._EventDateField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> EventDuration
        {
            get
            {
                return this._EventDurationField;
            }
            set
            {
                this._EventDurationField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> TradeMarkId
        {
            get
            {
                return this._TradeMarkIdField;
            }
            set
            {
                this._TradeMarkIdField = value;
            }
        }
        [XmlAttribute()]
        public decimal Value
        {
            get
            {
                return this._ValueField;
            }
            set
            {
                this._ValueField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<decimal> StandardValue
        {
            get
            {
                return this._StandardValueField;
            }
            set
            {
                this._StandardValueField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<decimal> PlannedValue
        {
            get
            {
                return this._PlannedValueField;
            }
            set
            {
                this._PlannedValueField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<decimal> ActualValue
        {
            get
            {
                return this._ActualValueField;
            }
            set
            {
                this._ActualValueField = value;
            }
        }
    }
}
