//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class CurrentUserView : DataItemView
    {
        public const string DataItemClassName = "CurrentUser";
        private string _FirstNameField;
        private string _MiddleNameField;
        private string _LastNameField;
        private string _WindowsIdentityField;
        private string _SqlIdentityField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public CurrentUserState State
        {
            get
            {
                return (CurrentUserState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public string FirstName
        {
            get
            {
                return this._FirstNameField;
            }
            set
            {
                this._FirstNameField = value;
            }
        }
        [XmlAttribute()]
        public string MiddleName
        {
            get
            {
                return this._MiddleNameField;
            }
            set
            {
                this._MiddleNameField = value;
            }
        }
        [XmlAttribute()]
        public string LastName
        {
            get
            {
                return this._LastNameField;
            }
            set
            {
                this._LastNameField = value;
            }
        }
        [XmlAttribute()]
        public string WindowsIdentity
        {
            get
            {
                return this._WindowsIdentityField;
            }
            set
            {
                this._WindowsIdentityField = value;
            }
        }
        [XmlAttribute()]
        public string SqlIdentity
        {
            get
            {
                return this._SqlIdentityField;
            }
            set
            {
                this._SqlIdentityField = value;
            }
        }
    }
}
