//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class DataQueryView : DataItemView
    {
        public const string DataItemClassName = "DataQuery";
        private string _DocumentElementField;
        private string _SelectorField;
        private string _ValueField;
        private string _SchemaNameField;
        private string _ProcedureNameField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public DataQueryState State
        {
            get
            {
                return (DataQueryState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public string DocumentElement
        {
            get
            {
                return this._DocumentElementField;
            }
            set
            {
                this._DocumentElementField = value;
            }
        }
        [XmlAttribute()]
        public string Selector
        {
            get
            {
                return this._SelectorField;
            }
            set
            {
                this._SelectorField = value;
            }
        }
        [XmlAttribute()]
        public string Value
        {
            get
            {
                return this._ValueField;
            }
            set
            {
                this._ValueField = value;
            }
        }
        [XmlAttribute()]
        public string SchemaName
        {
            get
            {
                return this._SchemaNameField;
            }
            set
            {
                this._SchemaNameField = value;
            }
        }
        [XmlAttribute()]
        public string ProcedureName
        {
            get
            {
                return this._ProcedureNameField;
            }
            set
            {
                this._ProcedureNameField = value;
            }
        }
    }
}
