//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class DocumentTypeEntryView : DataItemView
    {
        public const string DataItemClassName = "DocumentTypeEntry";
        private string _ClassNameField;
        private string _TableNameField;
        private string _SchemaNameField;
        private string _ClrTypeNameField;
        private string _DataAdapterTypeNameField;
        private string _DataAdapterModeField;
        private bool _IsNumberedField;
        private byte[] _SmallImageField;
        private byte[] _LargeImageField;
        private bool _SupportsTransitionTemplatesField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public DocumentTypeEntryState State
        {
            get
            {
                return (DocumentTypeEntryState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public string ClassName
        {
            get
            {
                return this._ClassNameField;
            }
            set
            {
                this._ClassNameField = value;
            }
        }
        [XmlAttribute()]
        public string TableName
        {
            get
            {
                return this._TableNameField;
            }
            set
            {
                this._TableNameField = value;
            }
        }
        [XmlAttribute()]
        public string SchemaName
        {
            get
            {
                return this._SchemaNameField;
            }
            set
            {
                this._SchemaNameField = value;
            }
        }
        [XmlAttribute()]
        public string ClrTypeName
        {
            get
            {
                return this._ClrTypeNameField;
            }
            set
            {
                this._ClrTypeNameField = value;
            }
        }
        [XmlAttribute()]
        public string DataAdapterTypeName
        {
            get
            {
                return this._DataAdapterTypeNameField;
            }
            set
            {
                this._DataAdapterTypeNameField = value;
            }
        }
        [XmlAttribute()]
        public string DataAdapterMode
        {
            get
            {
                return this._DataAdapterModeField;
            }
            set
            {
                this._DataAdapterModeField = value;
            }
        }
        [XmlAttribute()]
        public bool IsNumbered
        {
            get
            {
                return this._IsNumberedField;
            }
            set
            {
                this._IsNumberedField = value;
            }
        }
        [XmlAttribute()]
        public byte[] SmallImage
        {
            get
            {
                return this._SmallImageField;
            }
            set
            {
                this._SmallImageField = value;
            }
        }
        [XmlAttribute()]
        public byte[] LargeImage
        {
            get
            {
                return this._LargeImageField;
            }
            set
            {
                this._LargeImageField = value;
            }
        }
        [XmlAttribute()]
        public bool SupportsTransitionTemplates
        {
            get
            {
                return this._SupportsTransitionTemplatesField;
            }
            set
            {
                this._SupportsTransitionTemplatesField = value;
            }
        }
    }
}
