//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum DocumentNumberingRuleState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
        [XmlEnum("2")]
        Inactive = 2,
    }
    public partial class DocumentNumberingRule : DataItem
    {
        public const string DataItemClassName = "DocumentNumberingRule";
        public const string OrganizationIdProperty = "OrganizationId";
        public const string DocumentTypeIdProperty = "DocumentTypeId";
        public const string PeriodStartProperty = "PeriodStart";
        public const string PeriodEndProperty = "PeriodEnd";
        public const string ValueProperty = "Value";
        public const string IncrementProperty = "Increment";
        public const string FormatStringProperty = "FormatString";
        public const string FileAsFormatStringProperty = "FileAsFormatString";
        private int _OrganizationIdField;
        private int _DocumentTypeIdField;
        private System.Nullable<System.DateTime> _PeriodStartField;
        private System.Nullable<System.DateTime> _PeriodEndField;
        private int _ValueField;
        private int _IncrementField;
        private string _FormatStringField;
        private string _FileAsFormatStringField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public DocumentNumberingRuleState State
        {
            get
            {
                return (DocumentNumberingRuleState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="OrganizationId", IsNullable=false)]
        [XmlAttribute()]
        public int OrganizationId
        {
            get
            {
                return this._OrganizationIdField;
            }
            set
            {
                this._OrganizationIdField = value;
                InvokePropertyChanged("OrganizationId");
            }
        }
        [Column(Name="DocumentTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int DocumentTypeId
        {
            get
            {
                return this._DocumentTypeIdField;
            }
            set
            {
                this._DocumentTypeIdField = value;
                InvokePropertyChanged("DocumentTypeId");
            }
        }
        [Column(Name="PeriodStart", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<System.DateTime> PeriodStart
        {
            get
            {
                return this._PeriodStartField;
            }
            set
            {
                this._PeriodStartField = value;
                InvokePropertyChanged("PeriodStart");
            }
        }
        [Column(Name="PeriodEnd", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<System.DateTime> PeriodEnd
        {
            get
            {
                return this._PeriodEndField;
            }
            set
            {
                this._PeriodEndField = value;
                InvokePropertyChanged("PeriodEnd");
            }
        }
        [Column(Name="Value", IsNullable=false)]
        [XmlAttribute()]
        public int Value
        {
            get
            {
                return this._ValueField;
            }
            set
            {
                this._ValueField = value;
                InvokePropertyChanged("Value");
            }
        }
        [Column(Name="Increment", IsNullable=false)]
        [XmlAttribute()]
        public int Increment
        {
            get
            {
                return this._IncrementField;
            }
            set
            {
                this._IncrementField = value;
                InvokePropertyChanged("Increment");
            }
        }
        [Column(Name="FormatString", IsNullable=true, MaximumLength=256)]
        [XmlAttribute()]
        public string FormatString
        {
            get
            {
                return this._FormatStringField;
            }
            set
            {
                this._FormatStringField = value;
                InvokePropertyChanged("FormatString");
            }
        }
        [Column(Name="FileAsFormatString", IsNullable=true, MaximumLength=256)]
        [XmlAttribute()]
        public string FileAsFormatString
        {
            get
            {
                return this._FileAsFormatStringField;
            }
            set
            {
                this._FileAsFormatStringField = value;
                InvokePropertyChanged("FileAsFormatString");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
