//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum DocumentStateLogState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
    }
    public partial class DocumentStateLog : DataItem
    {
        public const string DataItemClassName = "DocumentStateLog";
        public const string DocumentTypeIdProperty = "DocumentTypeId";
        public const string DocumentIdProperty = "DocumentId";
        public const string FromStateProperty = "FromState";
        public const string ToStateProperty = "ToState";
        public const string DataProperty = "Data";
        private int _DocumentTypeIdField;
        private int _DocumentIdField;
        private byte _FromStateField;
        private byte _ToStateField;
        private string _DataField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [Column(Name="DocumentTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int DocumentTypeId
        {
            get
            {
                return this._DocumentTypeIdField;
            }
            set
            {
                this._DocumentTypeIdField = value;
                InvokePropertyChanged("DocumentTypeId");
            }
        }
        [Column(Name="DocumentId", IsNullable=false)]
        [XmlAttribute()]
        public int DocumentId
        {
            get
            {
                return this._DocumentIdField;
            }
            set
            {
                this._DocumentIdField = value;
                InvokePropertyChanged("DocumentId");
            }
        }
        [Column(Name="FromState", IsNullable=false)]
        [XmlAttribute()]
        public byte FromState
        {
            get
            {
                return this._FromStateField;
            }
            set
            {
                this._FromStateField = value;
                InvokePropertyChanged("FromState");
            }
        }
        [Column(Name="ToState", IsNullable=false)]
        [XmlAttribute()]
        public byte ToState
        {
            get
            {
                return this._ToStateField;
            }
            set
            {
                this._ToStateField = value;
                InvokePropertyChanged("ToState");
            }
        }
        [Column(Name="Data", IsNullable=true, MaximumLength=-1)]
        [XmlAttribute()]
        public string Data
        {
            get
            {
                return this._DataField;
            }
            set
            {
                this._DataField = value;
                InvokePropertyChanged("Data");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
