//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class DocumentEmployeeAccessRightView : DataItemView
    {
        public const string DataItemClassName = "DocumentEmployeeAccessRight";
        private int _DocumentTypeIdField;
        private int _DocumentIdField;
        private int _DocumentAccessTypeIdField;
        private int _EmployeeIdField;
        private System.Nullable<System.DateTime> _StartDateField;
        private System.Nullable<System.DateTime> _EndDateField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public DocumentEmployeeAccessRightState State
        {
            get
            {
                return (DocumentEmployeeAccessRightState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public int DocumentTypeId
        {
            get
            {
                return this._DocumentTypeIdField;
            }
            set
            {
                this._DocumentTypeIdField = value;
            }
        }
        [XmlAttribute()]
        public int DocumentId
        {
            get
            {
                return this._DocumentIdField;
            }
            set
            {
                this._DocumentIdField = value;
            }
        }
        [XmlAttribute()]
        public int DocumentAccessTypeId
        {
            get
            {
                return this._DocumentAccessTypeIdField;
            }
            set
            {
                this._DocumentAccessTypeIdField = value;
            }
        }
        [XmlAttribute()]
        public int EmployeeId
        {
            get
            {
                return this._EmployeeIdField;
            }
            set
            {
                this._EmployeeIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this._StartDateField;
            }
            set
            {
                this._StartDateField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this._EndDateField;
            }
            set
            {
                this._EndDateField = value;
            }
        }
    }
}
