//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class DocumentReportView : DataItemView
    {
        public const string DataItemClassName = "DocumentReport";
        private string _CodeField;
        private int _DocumentTypeIdField;
        private string _ReportPathField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public DocumentReportState State
        {
            get
            {
                return (DocumentReportState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public string Code
        {
            get
            {
                return this._CodeField;
            }
            set
            {
                this._CodeField = value;
            }
        }
        [XmlAttribute()]
        public int DocumentTypeId
        {
            get
            {
                return this._DocumentTypeIdField;
            }
            set
            {
                this._DocumentTypeIdField = value;
            }
        }
        [XmlAttribute()]
        public string ReportPath
        {
            get
            {
                return this._ReportPathField;
            }
            set
            {
                this._ReportPathField = value;
            }
        }
    }
}
