//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum DocumentReportState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
    }
    public partial class DocumentReport : DataItem
    {
        public const string DataItemClassName = "DocumentReport";
        public const string CodeProperty = "Code";
        public const string DocumentTypeIdProperty = "DocumentTypeId";
        public const string ReportPathProperty = "ReportPath";
        private string _CodeField;
        private int _DocumentTypeIdField;
        private string _ReportPathField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public DocumentReportState State
        {
            get
            {
                return (DocumentReportState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="Code", IsNullable=true, MaximumLength=128)]
        [XmlAttribute()]
        public string Code
        {
            get
            {
                return this._CodeField;
            }
            set
            {
                this._CodeField = value;
                InvokePropertyChanged("Code");
            }
        }
        [Column(Name="DocumentTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int DocumentTypeId
        {
            get
            {
                return this._DocumentTypeIdField;
            }
            set
            {
                this._DocumentTypeIdField = value;
                InvokePropertyChanged("DocumentTypeId");
            }
        }
        [Column(Name="ReportPath", IsNullable=false, MaximumLength=1024)]
        [XmlAttribute()]
        public string ReportPath
        {
            get
            {
                return this._ReportPathField;
            }
            set
            {
                this._ReportPathField = value;
                InvokePropertyChanged("ReportPath");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
