//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class EstimatesDocumentView : NumberedDataItemView
    {
        public const string DataItemClassName = "EstimatesDocument";
        private int _AccountIdField;
        private System.Nullable<int> _VenueProviderIdField;
        private int _ReasonIdField;
        private int _ServiceRequestTypeIdField;
        private int _ServiceRequestIdField;
        private int _VATRateIdField;
        private int _ExtraCostRateIdField;
        private decimal _CommissionField;
        private decimal _MarginField;
        private decimal _DiscountField;
        private System.Nullable<decimal> _TotalPriceField;
        private System.Nullable<decimal> _TotalCostField;
        private System.Nullable<decimal> _IncomeField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public EstimatesDocumentState State
        {
            get
            {
                return (EstimatesDocumentState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public int AccountId
        {
            get
            {
                return this._AccountIdField;
            }
            set
            {
                this._AccountIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> VenueProviderId
        {
            get
            {
                return this._VenueProviderIdField;
            }
            set
            {
                this._VenueProviderIdField = value;
            }
        }
        [XmlAttribute()]
        public int ReasonId
        {
            get
            {
                return this._ReasonIdField;
            }
            set
            {
                this._ReasonIdField = value;
            }
        }
        [XmlAttribute()]
        public int ServiceRequestTypeId
        {
            get
            {
                return this._ServiceRequestTypeIdField;
            }
            set
            {
                this._ServiceRequestTypeIdField = value;
            }
        }
        [XmlAttribute()]
        public int ServiceRequestId
        {
            get
            {
                return this._ServiceRequestIdField;
            }
            set
            {
                this._ServiceRequestIdField = value;
            }
        }
        [XmlAttribute()]
        public int VATRateId
        {
            get
            {
                return this._VATRateIdField;
            }
            set
            {
                this._VATRateIdField = value;
            }
        }
        [XmlAttribute()]
        public int ExtraCostRateId
        {
            get
            {
                return this._ExtraCostRateIdField;
            }
            set
            {
                this._ExtraCostRateIdField = value;
            }
        }
        [XmlAttribute()]
        public decimal Commission
        {
            get
            {
                return this._CommissionField;
            }
            set
            {
                this._CommissionField = value;
            }
        }
        [XmlAttribute()]
        public decimal Margin
        {
            get
            {
                return this._MarginField;
            }
            set
            {
                this._MarginField = value;
            }
        }
        [XmlAttribute()]
        public decimal Discount
        {
            get
            {
                return this._DiscountField;
            }
            set
            {
                this._DiscountField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<decimal> TotalPrice
        {
            get
            {
                return this._TotalPriceField;
            }
            set
            {
                this._TotalPriceField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<decimal> TotalCost
        {
            get
            {
                return this._TotalCostField;
            }
            set
            {
                this._TotalCostField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<decimal> Income
        {
            get
            {
                return this._IncomeField;
            }
            set
            {
                this._IncomeField = value;
            }
        }
    }
}
