//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class ItemColorView : DataItemView
    {
        public const string DataItemClassName = "ItemColor";
        private int _ColorSampleField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public ItemColorState State
        {
            get
            {
                return (ItemColorState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public int ColorSample
        {
            get
            {
                return this._ColorSampleField;
            }
            set
            {
                this._ColorSampleField = value;
            }
        }
    }
}
