//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum MoneyOperationState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Draft = 1,
        [XmlEnum("2")]
        Approved = 2,
        [XmlEnum("3")]
        Executed = 3,
    }
    public partial class MoneyOperation : NumberedDataItem
    {
        public const string DataItemClassName = "MoneyOperation";
        public const string ParentIdProperty = "ParentId";
        public const string BankAccountIdProperty = "BankAccountId";
        public const string MoneyOperationTypeIdProperty = "MoneyOperationTypeId";
        public const string MoneyOperationDirectionProperty = "MoneyOperationDirection";
        public const string BudgetIdProperty = "BudgetId";
        public const string OperatingBudgetIdProperty = "OperatingBudgetId";
        public const string BudgetItemGroupIdProperty = "BudgetItemGroupId";
        public const string BudgetItemIdProperty = "BudgetItemId";
        public const string PurchaseInvoiceIdProperty = "PurchaseInvoiceId";
        public const string SalesInvoiceIdProperty = "SalesInvoiceId";
        public const string AccountIdProperty = "AccountId";
        public const string EmployeeIdProperty = "EmployeeId";
        public const string SubjectProperty = "Subject";
        public const string ValueProperty = "Value";
        public const string VATRateIdProperty = "VATRateId";
        public const string VATValueProperty = "VATValue";
        private System.Nullable<int> _ParentIdField;
        private int _BankAccountIdField;
        private int _MoneyOperationTypeIdField;
        private int _MoneyOperationDirectionField;
        private System.Nullable<int> _BudgetIdField;
        private System.Nullable<int> _OperatingBudgetIdField;
        private System.Nullable<int> _BudgetItemGroupIdField;
        private System.Nullable<int> _BudgetItemIdField;
        private System.Nullable<int> _PurchaseInvoiceIdField;
        private System.Nullable<int> _SalesInvoiceIdField;
        private int _AccountIdField;
        private System.Nullable<int> _EmployeeIdField;
        private string _SubjectField;
        private decimal _ValueField;
        private System.Nullable<int> _VATRateIdField;
        private decimal _VATValueField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public MoneyOperationState State
        {
            get
            {
                return (MoneyOperationState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="ParentId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> ParentId
        {
            get
            {
                return this._ParentIdField;
            }
            set
            {
                this._ParentIdField = value;
                InvokePropertyChanged("ParentId");
            }
        }
        [Column(Name="BankAccountId", IsNullable=false)]
        [XmlAttribute()]
        public int BankAccountId
        {
            get
            {
                return this._BankAccountIdField;
            }
            set
            {
                this._BankAccountIdField = value;
                InvokePropertyChanged("BankAccountId");
            }
        }
        [Column(Name="MoneyOperationTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int MoneyOperationTypeId
        {
            get
            {
                return this._MoneyOperationTypeIdField;
            }
            set
            {
                this._MoneyOperationTypeIdField = value;
                InvokePropertyChanged("MoneyOperationTypeId");
            }
        }
        [Column(Name="MoneyOperationDirection", IsNullable=false)]
        [XmlAttribute()]
        public int MoneyOperationDirection
        {
            get
            {
                return this._MoneyOperationDirectionField;
            }
            set
            {
                this._MoneyOperationDirectionField = value;
                InvokePropertyChanged("MoneyOperationDirection");
            }
        }
        [Column(Name="BudgetId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> BudgetId
        {
            get
            {
                return this._BudgetIdField;
            }
            set
            {
                this._BudgetIdField = value;
                InvokePropertyChanged("BudgetId");
            }
        }
        [Column(Name="OperatingBudgetId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> OperatingBudgetId
        {
            get
            {
                return this._OperatingBudgetIdField;
            }
            set
            {
                this._OperatingBudgetIdField = value;
                InvokePropertyChanged("OperatingBudgetId");
            }
        }
        [Column(Name="BudgetItemGroupId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> BudgetItemGroupId
        {
            get
            {
                return this._BudgetItemGroupIdField;
            }
            set
            {
                this._BudgetItemGroupIdField = value;
                InvokePropertyChanged("BudgetItemGroupId");
            }
        }
        [Column(Name="BudgetItemId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> BudgetItemId
        {
            get
            {
                return this._BudgetItemIdField;
            }
            set
            {
                this._BudgetItemIdField = value;
                InvokePropertyChanged("BudgetItemId");
            }
        }
        [Column(Name="PurchaseInvoiceId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> PurchaseInvoiceId
        {
            get
            {
                return this._PurchaseInvoiceIdField;
            }
            set
            {
                this._PurchaseInvoiceIdField = value;
                InvokePropertyChanged("PurchaseInvoiceId");
            }
        }
        [Column(Name="SalesInvoiceId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> SalesInvoiceId
        {
            get
            {
                return this._SalesInvoiceIdField;
            }
            set
            {
                this._SalesInvoiceIdField = value;
                InvokePropertyChanged("SalesInvoiceId");
            }
        }
        [Column(Name="AccountId", IsNullable=false)]
        [XmlAttribute()]
        public int AccountId
        {
            get
            {
                return this._AccountIdField;
            }
            set
            {
                this._AccountIdField = value;
                InvokePropertyChanged("AccountId");
            }
        }
        [Column(Name="EmployeeId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> EmployeeId
        {
            get
            {
                return this._EmployeeIdField;
            }
            set
            {
                this._EmployeeIdField = value;
                InvokePropertyChanged("EmployeeId");
            }
        }
        [Column(Name="Subject", IsNullable=true, MaximumLength=1024)]
        [XmlAttribute()]
        public string Subject
        {
            get
            {
                return this._SubjectField;
            }
            set
            {
                this._SubjectField = value;
                InvokePropertyChanged("Subject");
            }
        }
        [Column(Name="Value", IsNullable=false)]
        [XmlAttribute()]
        public decimal Value
        {
            get
            {
                return this._ValueField;
            }
            set
            {
                this._ValueField = value;
                InvokePropertyChanged("Value");
            }
        }
        [Column(Name="VATRateId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> VATRateId
        {
            get
            {
                return this._VATRateIdField;
            }
            set
            {
                this._VATRateIdField = value;
                InvokePropertyChanged("VATRateId");
            }
        }
        [Column(Name="VATValue", IsNullable=false)]
        [XmlAttribute()]
        public decimal VATValue
        {
            get
            {
                return this._VATValueField;
            }
            set
            {
                this._VATValueField = value;
                InvokePropertyChanged("VATValue");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
