//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class OperatingBudgetFilter : Filter
    {
        public OperatingBudgetFilter()
        {
            this.States = new byte[] { (byte)OperatingBudgetState.Draft, (byte)OperatingBudgetState.PlannedApproved, (byte)OperatingBudgetState.ActualApproved, (byte)OperatingBudgetState.Closed};
        }
    }
}
