//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum OpportunityState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Prospecting = 1,
        [XmlEnum("2")]
        Proposal = 2,
        [XmlEnum("3")]
        Canceled = 3,
    }
    public partial class Opportunity : DataItem
    {
        public const string DataItemClassName = "Opportunity";
        public const string OrganizationIdProperty = "OrganizationId";
        public const string AssignedToEmployeeIdProperty = "AssignedToEmployeeId";
        public const string AccountIdProperty = "AccountId";
        public const string OpportunityTypeIdProperty = "OpportunityTypeId";
        public const string LeadSourceIdProperty = "LeadSourceId";
        public const string ProjectTypeIdProperty = "ProjectTypeId";
        public const string ReasonIdProperty = "ReasonId";
        public const string AmountOfGuestsProperty = "AmountOfGuests";
        public const string ValueProperty = "Value";
        public const string DateClosedProperty = "DateClosed";
        public const string EventDateProperty = "EventDate";
        public const string ProbabilityProperty = "Probability";
        private int _OrganizationIdField;
        private int _AssignedToEmployeeIdField;
        private int _AccountIdField;
        private int _OpportunityTypeIdField;
        private int _LeadSourceIdField;
        private int _ProjectTypeIdField;
        private int _ReasonIdField;
        private System.Nullable<int> _AmountOfGuestsField;
        private decimal _ValueField;
        private System.DateTime _DateClosedField;
        private System.DateTime _EventDateField;
        private decimal _ProbabilityField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public OpportunityState State
        {
            get
            {
                return (OpportunityState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="OrganizationId", IsNullable=false)]
        [XmlAttribute()]
        public int OrganizationId
        {
            get
            {
                return this._OrganizationIdField;
            }
            set
            {
                this._OrganizationIdField = value;
                InvokePropertyChanged("OrganizationId");
            }
        }
        [Column(Name="AssignedToEmployeeId", IsNullable=false)]
        [XmlAttribute()]
        public int AssignedToEmployeeId
        {
            get
            {
                return this._AssignedToEmployeeIdField;
            }
            set
            {
                this._AssignedToEmployeeIdField = value;
                InvokePropertyChanged("AssignedToEmployeeId");
            }
        }
        [Column(Name="AccountId", IsNullable=false)]
        [XmlAttribute()]
        public int AccountId
        {
            get
            {
                return this._AccountIdField;
            }
            set
            {
                this._AccountIdField = value;
                InvokePropertyChanged("AccountId");
            }
        }
        [Column(Name="OpportunityTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int OpportunityTypeId
        {
            get
            {
                return this._OpportunityTypeIdField;
            }
            set
            {
                this._OpportunityTypeIdField = value;
                InvokePropertyChanged("OpportunityTypeId");
            }
        }
        [Column(Name="LeadSourceId", IsNullable=false)]
        [XmlAttribute()]
        public int LeadSourceId
        {
            get
            {
                return this._LeadSourceIdField;
            }
            set
            {
                this._LeadSourceIdField = value;
                InvokePropertyChanged("LeadSourceId");
            }
        }
        [Column(Name="ProjectTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int ProjectTypeId
        {
            get
            {
                return this._ProjectTypeIdField;
            }
            set
            {
                this._ProjectTypeIdField = value;
                InvokePropertyChanged("ProjectTypeId");
            }
        }
        [Column(Name="ReasonId", IsNullable=false)]
        [XmlAttribute()]
        public int ReasonId
        {
            get
            {
                return this._ReasonIdField;
            }
            set
            {
                this._ReasonIdField = value;
                InvokePropertyChanged("ReasonId");
            }
        }
        [Column(Name="AmountOfGuests", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> AmountOfGuests
        {
            get
            {
                return this._AmountOfGuestsField;
            }
            set
            {
                this._AmountOfGuestsField = value;
                InvokePropertyChanged("AmountOfGuests");
            }
        }
        [Column(Name="Value", IsNullable=false)]
        [XmlAttribute()]
        public decimal Value
        {
            get
            {
                return this._ValueField;
            }
            set
            {
                this._ValueField = value;
                InvokePropertyChanged("Value");
            }
        }
        [Column(Name="DateClosed", IsNullable=false)]
        [XmlAttribute()]
        public System.DateTime DateClosed
        {
            get
            {
                return this._DateClosedField;
            }
            set
            {
                this._DateClosedField = value;
                InvokePropertyChanged("DateClosed");
            }
        }
        [Column(Name="EventDate", IsNullable=false)]
        [XmlAttribute()]
        public System.DateTime EventDate
        {
            get
            {
                return this._EventDateField;
            }
            set
            {
                this._EventDateField = value;
                InvokePropertyChanged("EventDate");
            }
        }
        [Column(Name="Probability", IsNullable=false)]
        [XmlAttribute()]
        public decimal Probability
        {
            get
            {
                return this._ProbabilityField;
            }
            set
            {
                this._ProbabilityField = value;
                InvokePropertyChanged("Probability");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
