//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum OrganizationState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
        [XmlEnum("2")]
        Inactive = 2,
    }
    public partial class Organization : DataItem
    {
        public const string DataItemClassName = "Organization";
        public const string FullNameProperty = "FullName";
        public const string MemberOfAccountIdProperty = "MemberOfAccountId";
        public const string AccountTypeIdProperty = "AccountTypeId";
        public const string PhoneProperty = "Phone";
        public const string OtherPhoneProperty = "OtherPhone";
        public const string FaxProperty = "Fax";
        public const string EmailProperty = "Email";
        public const string OtherEmailProperty = "OtherEmail";
        public const string WebSiteProperty = "WebSite";
        public const string ProjectTemplateIdProperty = "ProjectTemplateId";
        public const string ExecutiveIdProperty = "ExecutiveId";
        public const string AccountantIdProperty = "AccountantId";
        public const string BillingAddressStreetProperty = "BillingAddressStreet";
        public const string BillingAddressCityProperty = "BillingAddressCity";
        public const string BillingAddressRegionProperty = "BillingAddressRegion";
        public const string BillingAddressPostalCodeProperty = "BillingAddressPostalCode";
        public const string BillingAddressCountryProperty = "BillingAddressCountry";
        public const string ShippingAddressStreetProperty = "ShippingAddressStreet";
        public const string ShippingAddressCityProperty = "ShippingAddressCity";
        public const string ShippingAddressRegionProperty = "ShippingAddressRegion";
        public const string ShippingAddressPostalCodeProperty = "ShippingAddressPostalCode";
        public const string ShippingAddressCountryProperty = "ShippingAddressCountry";
        private string _FullNameField;
        private System.Nullable<int> _MemberOfAccountIdField;
        private int _AccountTypeIdField;
        private string _PhoneField;
        private string _OtherPhoneField;
        private string _FaxField;
        private string _EmailField;
        private string _OtherEmailField;
        private string _WebSiteField;
        private System.Nullable<int> _ProjectTemplateIdField;
        private System.Nullable<int> _ExecutiveIdField;
        private System.Nullable<int> _AccountantIdField;
        private string _BillingAddressStreetField;
        private string _BillingAddressCityField;
        private string _BillingAddressRegionField;
        private string _BillingAddressPostalCodeField;
        private string _BillingAddressCountryField;
        private string _ShippingAddressStreetField;
        private string _ShippingAddressCityField;
        private string _ShippingAddressRegionField;
        private string _ShippingAddressPostalCodeField;
        private string _ShippingAddressCountryField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public OrganizationState State
        {
            get
            {
                return (OrganizationState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="FullName", IsNullable=true, MaximumLength=1024)]
        [XmlAttribute()]
        public string FullName
        {
            get
            {
                return this._FullNameField;
            }
            set
            {
                this._FullNameField = value;
                InvokePropertyChanged("FullName");
            }
        }
        [Column(Name="MemberOfAccountId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> MemberOfAccountId
        {
            get
            {
                return this._MemberOfAccountIdField;
            }
            set
            {
                this._MemberOfAccountIdField = value;
                InvokePropertyChanged("MemberOfAccountId");
            }
        }
        [Column(Name="AccountTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int AccountTypeId
        {
            get
            {
                return this._AccountTypeIdField;
            }
            set
            {
                this._AccountTypeIdField = value;
                InvokePropertyChanged("AccountTypeId");
            }
        }
        [Column(Name="Phone", IsNullable=true, MaximumLength=128)]
        [XmlAttribute()]
        public string Phone
        {
            get
            {
                return this._PhoneField;
            }
            set
            {
                this._PhoneField = value;
                InvokePropertyChanged("Phone");
            }
        }
        [Column(Name="OtherPhone", IsNullable=true, MaximumLength=128)]
        [XmlAttribute()]
        public string OtherPhone
        {
            get
            {
                return this._OtherPhoneField;
            }
            set
            {
                this._OtherPhoneField = value;
                InvokePropertyChanged("OtherPhone");
            }
        }
        [Column(Name="Fax", IsNullable=true, MaximumLength=128)]
        [XmlAttribute()]
        public string Fax
        {
            get
            {
                return this._FaxField;
            }
            set
            {
                this._FaxField = value;
                InvokePropertyChanged("Fax");
            }
        }
        [Column(Name="Email", IsNullable=true, MaximumLength=128)]
        [XmlAttribute()]
        public string Email
        {
            get
            {
                return this._EmailField;
            }
            set
            {
                this._EmailField = value;
                InvokePropertyChanged("Email");
            }
        }
        [Column(Name="OtherEmail", IsNullable=true, MaximumLength=128)]
        [XmlAttribute()]
        public string OtherEmail
        {
            get
            {
                return this._OtherEmailField;
            }
            set
            {
                this._OtherEmailField = value;
                InvokePropertyChanged("OtherEmail");
            }
        }
        [Column(Name="WebSite", IsNullable=true, MaximumLength=128)]
        [XmlAttribute()]
        public string WebSite
        {
            get
            {
                return this._WebSiteField;
            }
            set
            {
                this._WebSiteField = value;
                InvokePropertyChanged("WebSite");
            }
        }
        [Column(Name="ProjectTemplateId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> ProjectTemplateId
        {
            get
            {
                return this._ProjectTemplateIdField;
            }
            set
            {
                this._ProjectTemplateIdField = value;
                InvokePropertyChanged("ProjectTemplateId");
            }
        }
        [Column(Name="ExecutiveId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> ExecutiveId
        {
            get
            {
                return this._ExecutiveIdField;
            }
            set
            {
                this._ExecutiveIdField = value;
                InvokePropertyChanged("ExecutiveId");
            }
        }
        [Column(Name="AccountantId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> AccountantId
        {
            get
            {
                return this._AccountantIdField;
            }
            set
            {
                this._AccountantIdField = value;
                InvokePropertyChanged("AccountantId");
            }
        }
        [Column(Name="BillingAddressStreet", IsNullable=true, MaximumLength=256)]
        [XmlAttribute()]
        public string BillingAddressStreet
        {
            get
            {
                return this._BillingAddressStreetField;
            }
            set
            {
                this._BillingAddressStreetField = value;
                InvokePropertyChanged("BillingAddressStreet");
            }
        }
        [Column(Name="BillingAddressCity", IsNullable=true, MaximumLength=64)]
        [XmlAttribute()]
        public string BillingAddressCity
        {
            get
            {
                return this._BillingAddressCityField;
            }
            set
            {
                this._BillingAddressCityField = value;
                InvokePropertyChanged("BillingAddressCity");
            }
        }
        [Column(Name="BillingAddressRegion", IsNullable=true, MaximumLength=64)]
        [XmlAttribute()]
        public string BillingAddressRegion
        {
            get
            {
                return this._BillingAddressRegionField;
            }
            set
            {
                this._BillingAddressRegionField = value;
                InvokePropertyChanged("BillingAddressRegion");
            }
        }
        [Column(Name="BillingAddressPostalCode", IsNullable=true, MaximumLength=10)]
        [XmlAttribute()]
        public string BillingAddressPostalCode
        {
            get
            {
                return this._BillingAddressPostalCodeField;
            }
            set
            {
                this._BillingAddressPostalCodeField = value;
                InvokePropertyChanged("BillingAddressPostalCode");
            }
        }
        [Column(Name="BillingAddressCountry", IsNullable=true, MaximumLength=64)]
        [XmlAttribute()]
        public string BillingAddressCountry
        {
            get
            {
                return this._BillingAddressCountryField;
            }
            set
            {
                this._BillingAddressCountryField = value;
                InvokePropertyChanged("BillingAddressCountry");
            }
        }
        [Column(Name="ShippingAddressStreet", IsNullable=true, MaximumLength=256)]
        [XmlAttribute()]
        public string ShippingAddressStreet
        {
            get
            {
                return this._ShippingAddressStreetField;
            }
            set
            {
                this._ShippingAddressStreetField = value;
                InvokePropertyChanged("ShippingAddressStreet");
            }
        }
        [Column(Name="ShippingAddressCity", IsNullable=true, MaximumLength=64)]
        [XmlAttribute()]
        public string ShippingAddressCity
        {
            get
            {
                return this._ShippingAddressCityField;
            }
            set
            {
                this._ShippingAddressCityField = value;
                InvokePropertyChanged("ShippingAddressCity");
            }
        }
        [Column(Name="ShippingAddressRegion", IsNullable=true, MaximumLength=64)]
        [XmlAttribute()]
        public string ShippingAddressRegion
        {
            get
            {
                return this._ShippingAddressRegionField;
            }
            set
            {
                this._ShippingAddressRegionField = value;
                InvokePropertyChanged("ShippingAddressRegion");
            }
        }
        [Column(Name="ShippingAddressPostalCode", IsNullable=true, MaximumLength=10)]
        [XmlAttribute()]
        public string ShippingAddressPostalCode
        {
            get
            {
                return this._ShippingAddressPostalCodeField;
            }
            set
            {
                this._ShippingAddressPostalCodeField = value;
                InvokePropertyChanged("ShippingAddressPostalCode");
            }
        }
        [Column(Name="ShippingAddressCountry", IsNullable=true, MaximumLength=64)]
        [XmlAttribute()]
        public string ShippingAddressCountry
        {
            get
            {
                return this._ShippingAddressCountryField;
            }
            set
            {
                this._ShippingAddressCountryField = value;
                InvokePropertyChanged("ShippingAddressCountry");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
