//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum ProjectState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Draft = 1,
        [XmlEnum("2")]
        Accepted = 2,
        [XmlEnum("3")]
        Completed = 3,
        [XmlEnum("4")]
        Canceled = 4,
    }
    public partial class Project : DataItem
    {
        public const string DataItemClassName = "Project";
        public const string CodeProperty = "Code";
        public const string ProjectTypeIdProperty = "ProjectTypeId";
        public const string OpportunityIdProperty = "OpportunityId";
        public const string OrganizationIdProperty = "OrganizationId";
        public const string AccountIdProperty = "AccountId";
        public const string ResponsibleContactIdProperty = "ResponsibleContactId";
        public const string ContractIdProperty = "ContractId";
        public const string StartDateProperty = "StartDate";
        public const string EndDateProperty = "EndDate";
        private string _CodeField;
        private int _ProjectTypeIdField;
        private System.Nullable<int> _OpportunityIdField;
        private int _OrganizationIdField;
        private System.Nullable<int> _AccountIdField;
        private System.Nullable<int> _ResponsibleContactIdField;
        private System.Nullable<int> _ContractIdField;
        private System.DateTime _StartDateField;
        private System.DateTime _EndDateField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public ProjectState State
        {
            get
            {
                return (ProjectState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="Code", IsNullable=false, MaximumLength=32)]
        [XmlAttribute()]
        public string Code
        {
            get
            {
                return this._CodeField;
            }
            set
            {
                this._CodeField = value;
                InvokePropertyChanged("Code");
            }
        }
        [Column(Name="ProjectTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int ProjectTypeId
        {
            get
            {
                return this._ProjectTypeIdField;
            }
            set
            {
                this._ProjectTypeIdField = value;
                InvokePropertyChanged("ProjectTypeId");
            }
        }
        [Column(Name="OpportunityId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> OpportunityId
        {
            get
            {
                return this._OpportunityIdField;
            }
            set
            {
                this._OpportunityIdField = value;
                InvokePropertyChanged("OpportunityId");
            }
        }
        [Column(Name="OrganizationId", IsNullable=false)]
        [XmlAttribute()]
        public int OrganizationId
        {
            get
            {
                return this._OrganizationIdField;
            }
            set
            {
                this._OrganizationIdField = value;
                InvokePropertyChanged("OrganizationId");
            }
        }
        [Column(Name="AccountId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> AccountId
        {
            get
            {
                return this._AccountIdField;
            }
            set
            {
                this._AccountIdField = value;
                InvokePropertyChanged("AccountId");
            }
        }
        [Column(Name="ResponsibleContactId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> ResponsibleContactId
        {
            get
            {
                return this._ResponsibleContactIdField;
            }
            set
            {
                this._ResponsibleContactIdField = value;
                InvokePropertyChanged("ResponsibleContactId");
            }
        }
        [Column(Name="ContractId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> ContractId
        {
            get
            {
                return this._ContractIdField;
            }
            set
            {
                this._ContractIdField = value;
                InvokePropertyChanged("ContractId");
            }
        }
        [Column(Name="StartDate", IsNullable=false)]
        [XmlAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this._StartDateField;
            }
            set
            {
                this._StartDateField = value;
                InvokePropertyChanged("StartDate");
            }
        }
        [Column(Name="EndDate", IsNullable=false)]
        [XmlAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this._EndDateField;
            }
            set
            {
                this._EndDateField = value;
                InvokePropertyChanged("EndDate");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
