//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class ProjectTaskView : DataItemView
    {
        public const string DataItemClassName = "ProjectTask";
        private int _TaskNoField;
        private int _ProjectIdField;
        private string _ServiceRequestNumberField;
        private System.Nullable<int> _ServiceRequestAccountIdField;
        private System.Nullable<int> _ProjectMemberRoleIdField;
        private System.Nullable<int> _AssignedToEmployeeIdField;
        private System.Nullable<int> _ProjectTaskStatusIdField;
        private string _ProjectTaskStatusField;
        private System.Nullable<int> _ColorField;
        private bool _IsMilestoneField;
        private System.DateTime _TaskStartField;
        private System.DateTime _TaskFinishField;
        private int _ImportanceField;
        private decimal _CompleteField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public ProjectTaskState State
        {
            get
            {
                return (ProjectTaskState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public int TaskNo
        {
            get
            {
                return this._TaskNoField;
            }
            set
            {
                this._TaskNoField = value;
            }
        }
        [XmlAttribute()]
        public int ProjectId
        {
            get
            {
                return this._ProjectIdField;
            }
            set
            {
                this._ProjectIdField = value;
            }
        }
        [XmlAttribute()]
        public string ServiceRequestNumber
        {
            get
            {
                return this._ServiceRequestNumberField;
            }
            set
            {
                this._ServiceRequestNumberField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> ServiceRequestAccountId
        {
            get
            {
                return this._ServiceRequestAccountIdField;
            }
            set
            {
                this._ServiceRequestAccountIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> ProjectMemberRoleId
        {
            get
            {
                return this._ProjectMemberRoleIdField;
            }
            set
            {
                this._ProjectMemberRoleIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> AssignedToEmployeeId
        {
            get
            {
                return this._AssignedToEmployeeIdField;
            }
            set
            {
                this._AssignedToEmployeeIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> ProjectTaskStatusId
        {
            get
            {
                return this._ProjectTaskStatusIdField;
            }
            set
            {
                this._ProjectTaskStatusIdField = value;
            }
        }
        [XmlAttribute()]
        public string ProjectTaskStatus
        {
            get
            {
                return this._ProjectTaskStatusField;
            }
            set
            {
                this._ProjectTaskStatusField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> Color
        {
            get
            {
                return this._ColorField;
            }
            set
            {
                this._ColorField = value;
            }
        }
        [XmlAttribute()]
        public bool IsMilestone
        {
            get
            {
                return this._IsMilestoneField;
            }
            set
            {
                this._IsMilestoneField = value;
            }
        }
        [XmlAttribute()]
        public System.DateTime TaskStart
        {
            get
            {
                return this._TaskStartField;
            }
            set
            {
                this._TaskStartField = value;
            }
        }
        [XmlAttribute()]
        public System.DateTime TaskFinish
        {
            get
            {
                return this._TaskFinishField;
            }
            set
            {
                this._TaskFinishField = value;
            }
        }
        [XmlAttribute()]
        public int Importance
        {
            get
            {
                return this._ImportanceField;
            }
            set
            {
                this._ImportanceField = value;
            }
        }
        [XmlAttribute()]
        public decimal Complete
        {
            get
            {
                return this._CompleteField;
            }
            set
            {
                this._CompleteField = value;
            }
        }
    }
}
