//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum ProjectTaskState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Draft = 1,
        [XmlEnum("2")]
        Assigned = 2,
        [XmlEnum("3")]
        Canceled = 3,
        [XmlEnum("4")]
        Completed = 4,
    }
    public partial class ProjectTask : DataItem
    {
        public const string DataItemClassName = "ProjectTask";
        public const string TaskNoProperty = "TaskNo";
        public const string ProjectIdProperty = "ProjectId";
        public const string ProjectMemberRoleIdProperty = "ProjectMemberRoleId";
        public const string AssignedToEmployeeIdProperty = "AssignedToEmployeeId";
        public const string ProjectTaskStatusIdProperty = "ProjectTaskStatusId";
        public const string ProjectTaskStatusProperty = "ProjectTaskStatus";
        public const string IsMilestoneProperty = "IsMilestone";
        public const string TaskStartProperty = "TaskStart";
        public const string TaskFinishProperty = "TaskFinish";
        public const string ImportanceProperty = "Importance";
        public const string CompleteProperty = "Complete";
        private int _TaskNoField;
        private int _ProjectIdField;
        private System.Nullable<int> _ProjectMemberRoleIdField;
        private System.Nullable<int> _AssignedToEmployeeIdField;
        private System.Nullable<int> _ProjectTaskStatusIdField;
        private string _ProjectTaskStatusField;
        private bool _IsMilestoneField;
        private System.DateTime _TaskStartField;
        private System.DateTime _TaskFinishField;
        private int _ImportanceField;
        private decimal _CompleteField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public ProjectTaskState State
        {
            get
            {
                return (ProjectTaskState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="TaskNo", IsNullable=false)]
        [XmlAttribute()]
        public int TaskNo
        {
            get
            {
                return this._TaskNoField;
            }
            set
            {
                this._TaskNoField = value;
                InvokePropertyChanged("TaskNo");
            }
        }
        [Column(Name="ProjectId", IsNullable=false)]
        [XmlAttribute()]
        public int ProjectId
        {
            get
            {
                return this._ProjectIdField;
            }
            set
            {
                this._ProjectIdField = value;
                InvokePropertyChanged("ProjectId");
            }
        }
        [Column(Name="ProjectMemberRoleId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> ProjectMemberRoleId
        {
            get
            {
                return this._ProjectMemberRoleIdField;
            }
            set
            {
                this._ProjectMemberRoleIdField = value;
                InvokePropertyChanged("ProjectMemberRoleId");
            }
        }
        [Column(Name="AssignedToEmployeeId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> AssignedToEmployeeId
        {
            get
            {
                return this._AssignedToEmployeeIdField;
            }
            set
            {
                this._AssignedToEmployeeIdField = value;
                InvokePropertyChanged("AssignedToEmployeeId");
            }
        }
        [Column(Name="ProjectTaskStatusId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> ProjectTaskStatusId
        {
            get
            {
                return this._ProjectTaskStatusIdField;
            }
            set
            {
                this._ProjectTaskStatusIdField = value;
                InvokePropertyChanged("ProjectTaskStatusId");
            }
        }
        [Column(Name="ProjectTaskStatus", IsNullable=true, MaximumLength=1024)]
        [XmlAttribute()]
        public string ProjectTaskStatus
        {
            get
            {
                return this._ProjectTaskStatusField;
            }
            set
            {
                this._ProjectTaskStatusField = value;
                InvokePropertyChanged("ProjectTaskStatus");
            }
        }
        [Column(Name="IsMilestone", IsNullable=false)]
        [XmlAttribute()]
        public bool IsMilestone
        {
            get
            {
                return this._IsMilestoneField;
            }
            set
            {
                this._IsMilestoneField = value;
                InvokePropertyChanged("IsMilestone");
            }
        }
        [Column(Name="TaskStart", IsNullable=false)]
        [XmlAttribute()]
        public System.DateTime TaskStart
        {
            get
            {
                return this._TaskStartField;
            }
            set
            {
                this._TaskStartField = value;
                InvokePropertyChanged("TaskStart");
            }
        }
        [Column(Name="TaskFinish", IsNullable=false)]
        [XmlAttribute()]
        public System.DateTime TaskFinish
        {
            get
            {
                return this._TaskFinishField;
            }
            set
            {
                this._TaskFinishField = value;
                InvokePropertyChanged("TaskFinish");
            }
        }
        [Column(Name="Importance", IsNullable=false)]
        [XmlAttribute()]
        public int Importance
        {
            get
            {
                return this._ImportanceField;
            }
            set
            {
                this._ImportanceField = value;
                InvokePropertyChanged("Importance");
            }
        }
        [Column(Name="Complete", IsNullable=false)]
        [XmlAttribute()]
        public decimal Complete
        {
            get
            {
                return this._CompleteField;
            }
            set
            {
                this._CompleteField = value;
                InvokePropertyChanged("Complete");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
