//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum ProjectTaskStatusState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
        [XmlEnum("2")]
        Inactive = 2,
    }
    public partial class ProjectTaskStatus : DataItem
    {
        public const string DataItemClassName = "ProjectTaskStatus";
        public const string ColorProperty = "Color";
        public const string CompleteProperty = "Complete";
        public const string ProjectTaskStateProperty = "ProjectTaskState";
        private int _ColorField;
        private decimal _CompleteField;
        private byte _ProjectTaskStateField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public ProjectTaskStatusState State
        {
            get
            {
                return (ProjectTaskStatusState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="Color", IsNullable=false)]
        [XmlAttribute()]
        public int Color
        {
            get
            {
                return this._ColorField;
            }
            set
            {
                this._ColorField = value;
                InvokePropertyChanged("Color");
            }
        }
        [Column(Name="Complete", IsNullable=false)]
        [XmlAttribute()]
        public decimal Complete
        {
            get
            {
                return this._CompleteField;
            }
            set
            {
                this._CompleteField = value;
                InvokePropertyChanged("Complete");
            }
        }
        [Column(Name="ProjectTaskState", IsNullable=false)]
        [XmlAttribute()]
        public byte ProjectTaskState
        {
            get
            {
                return this._ProjectTaskStateField;
            }
            set
            {
                this._ProjectTaskStateField = value;
                InvokePropertyChanged("ProjectTaskState");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
