//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class PurchaseOrderView : NumberedDataItemView
    {
        public const string DataItemClassName = "PurchaseOrder";
        private int _StoragePlaceIdField;
        private int _SupplierIdField;
        private System.Nullable<int> _PurchaseInvoiceIdField;
        private decimal _TotalCostField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public PurchaseOrderState State
        {
            get
            {
                return (PurchaseOrderState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public int StoragePlaceId
        {
            get
            {
                return this._StoragePlaceIdField;
            }
            set
            {
                this._StoragePlaceIdField = value;
            }
        }
        [XmlAttribute()]
        public int SupplierId
        {
            get
            {
                return this._SupplierIdField;
            }
            set
            {
                this._SupplierIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> PurchaseInvoiceId
        {
            get
            {
                return this._PurchaseInvoiceIdField;
            }
            set
            {
                this._PurchaseInvoiceIdField = value;
            }
        }
        [XmlAttribute()]
        public decimal TotalCost
        {
            get
            {
                return this._TotalCostField;
            }
            set
            {
                this._TotalCostField = value;
            }
        }
    }
}
