//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class PurchaseInvoiceView : NumberedDataItemView
    {
        public const string DataItemClassName = "PurchaseInvoice";
        private System.Nullable<System.DateTime> _DueDateField;
        private int _AccountIdField;
        private System.Nullable<int> _ServiceRequestIdField;
        private System.Nullable<int> _ServiceRequestAccountIdField;
        private System.Nullable<System.DateTime> _OperatingBudgetDocumentDateField;
        private System.Nullable<int> _BudgetIdField;
        private System.Nullable<int> _OperatingBudgetIdField;
        private int _BudgetItemGroupIdField;
        private System.Nullable<int> _BudgetItemIdField;
        private int _ResponsibleEmployeeIdField;
        private string _SubjectField;
        private bool _IsCashField;
        private decimal _ValueField;
        private decimal _VATValueField;
        private decimal _PayedValueField;
        private System.Nullable<int> _VATRateIdField;
        private decimal _PayedVATValueField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public PurchaseInvoiceState State
        {
            get
            {
                return (PurchaseInvoiceState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<System.DateTime> DueDate
        {
            get
            {
                return this._DueDateField;
            }
            set
            {
                this._DueDateField = value;
            }
        }
        [XmlAttribute()]
        public int AccountId
        {
            get
            {
                return this._AccountIdField;
            }
            set
            {
                this._AccountIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> ServiceRequestId
        {
            get
            {
                return this._ServiceRequestIdField;
            }
            set
            {
                this._ServiceRequestIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> ServiceRequestAccountId
        {
            get
            {
                return this._ServiceRequestAccountIdField;
            }
            set
            {
                this._ServiceRequestAccountIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<System.DateTime> OperatingBudgetDocumentDate
        {
            get
            {
                return this._OperatingBudgetDocumentDateField;
            }
            set
            {
                this._OperatingBudgetDocumentDateField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> BudgetId
        {
            get
            {
                return this._BudgetIdField;
            }
            set
            {
                this._BudgetIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> OperatingBudgetId
        {
            get
            {
                return this._OperatingBudgetIdField;
            }
            set
            {
                this._OperatingBudgetIdField = value;
            }
        }
        [XmlAttribute()]
        public int BudgetItemGroupId
        {
            get
            {
                return this._BudgetItemGroupIdField;
            }
            set
            {
                this._BudgetItemGroupIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> BudgetItemId
        {
            get
            {
                return this._BudgetItemIdField;
            }
            set
            {
                this._BudgetItemIdField = value;
            }
        }
        [XmlAttribute()]
        public int ResponsibleEmployeeId
        {
            get
            {
                return this._ResponsibleEmployeeIdField;
            }
            set
            {
                this._ResponsibleEmployeeIdField = value;
            }
        }
        [XmlAttribute()]
        public string Subject
        {
            get
            {
                return this._SubjectField;
            }
            set
            {
                this._SubjectField = value;
            }
        }
        [XmlAttribute()]
        public bool IsCash
        {
            get
            {
                return this._IsCashField;
            }
            set
            {
                this._IsCashField = value;
            }
        }
        [XmlAttribute()]
        public decimal Value
        {
            get
            {
                return this._ValueField;
            }
            set
            {
                this._ValueField = value;
            }
        }
        [XmlAttribute()]
        public decimal VATValue
        {
            get
            {
                return this._VATValueField;
            }
            set
            {
                this._VATValueField = value;
            }
        }
        [XmlAttribute()]
        public decimal PayedValue
        {
            get
            {
                return this._PayedValueField;
            }
            set
            {
                this._PayedValueField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> VATRateId
        {
            get
            {
                return this._VATRateIdField;
            }
            set
            {
                this._VATRateIdField = value;
            }
        }
        [XmlAttribute()]
        public decimal PayedVATValue
        {
            get
            {
                return this._PayedVATValueField;
            }
            set
            {
                this._PayedVATValueField = value;
            }
        }
    }
}
