//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class ReminderView : DataItemView
    {
        public const string DataItemClassName = "Reminder";
        private System.DateTime _StartDateField;
        private System.DateTime _DueDateField;
        private System.DateTime _ReminderTimeField;
        private int _UserIdField;
        private System.Nullable<int> _DocumentTypeIdField;
        private System.Nullable<int> _DocumentIdField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public ReminderState State
        {
            get
            {
                return (ReminderState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this._StartDateField;
            }
            set
            {
                this._StartDateField = value;
            }
        }
        [XmlAttribute()]
        public System.DateTime DueDate
        {
            get
            {
                return this._DueDateField;
            }
            set
            {
                this._DueDateField = value;
            }
        }
        [XmlAttribute()]
        public System.DateTime ReminderTime
        {
            get
            {
                return this._ReminderTimeField;
            }
            set
            {
                this._ReminderTimeField = value;
            }
        }
        [XmlAttribute()]
        public int UserId
        {
            get
            {
                return this._UserIdField;
            }
            set
            {
                this._UserIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> DocumentTypeId
        {
            get
            {
                return this._DocumentTypeIdField;
            }
            set
            {
                this._DocumentTypeIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> DocumentId
        {
            get
            {
                return this._DocumentIdField;
            }
            set
            {
                this._DocumentIdField = value;
            }
        }
    }
}
