//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class ReturnStatementView : NumberedDataItemView
    {
        public const string DataItemClassName = "ReturnStatement";
        private int _StoragePlaceIdField;
        private int _SalesOrderIdField;
        private System.Nullable<int> _BudgetIdField;
        private int _CustomerIdField;
        private decimal _TotalCostField;
        private decimal _TotalPriceField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public ReturnStatementState State
        {
            get
            {
                return (ReturnStatementState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public int StoragePlaceId
        {
            get
            {
                return this._StoragePlaceIdField;
            }
            set
            {
                this._StoragePlaceIdField = value;
            }
        }
        [XmlAttribute()]
        public int SalesOrderId
        {
            get
            {
                return this._SalesOrderIdField;
            }
            set
            {
                this._SalesOrderIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> BudgetId
        {
            get
            {
                return this._BudgetIdField;
            }
            set
            {
                this._BudgetIdField = value;
            }
        }
        [XmlAttribute()]
        public int CustomerId
        {
            get
            {
                return this._CustomerIdField;
            }
            set
            {
                this._CustomerIdField = value;
            }
        }
        [XmlAttribute()]
        public decimal TotalCost
        {
            get
            {
                return this._TotalCostField;
            }
            set
            {
                this._TotalCostField = value;
            }
        }
        [XmlAttribute()]
        public decimal TotalPrice
        {
            get
            {
                return this._TotalPriceField;
            }
            set
            {
                this._TotalPriceField = value;
            }
        }
    }
}
