//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.Xml.Serialization;
    
    public partial class SalesOrderView : NumberedDataItemView
    {
        public const string DataItemClassName = "SalesOrder";
        private int _StoragePlaceIdField;
        private System.Nullable<int> _BudgetIdField;
        private string _BudgetNumberField;
        private System.Nullable<System.DateTime> _EventDateField;
        private System.Nullable<int> _ServiceRequestAccountIdField;
        private string _ServiceRequestNumberField;
        private System.Nullable<int> _BudgetItemGroupIdField;
        private System.Nullable<int> _BudgetItemIdField;
        private int _CustomerIdField;
        private decimal _TotalCostField;
        private decimal _TotalPriceField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public SalesOrderState State
        {
            get
            {
                return (SalesOrderState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [XmlAttribute()]
        public int StoragePlaceId
        {
            get
            {
                return this._StoragePlaceIdField;
            }
            set
            {
                this._StoragePlaceIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> BudgetId
        {
            get
            {
                return this._BudgetIdField;
            }
            set
            {
                this._BudgetIdField = value;
            }
        }
        [XmlAttribute()]
        public string BudgetNumber
        {
            get
            {
                return this._BudgetNumberField;
            }
            set
            {
                this._BudgetNumberField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<System.DateTime> EventDate
        {
            get
            {
                return this._EventDateField;
            }
            set
            {
                this._EventDateField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> ServiceRequestAccountId
        {
            get
            {
                return this._ServiceRequestAccountIdField;
            }
            set
            {
                this._ServiceRequestAccountIdField = value;
            }
        }
        [XmlAttribute()]
        public string ServiceRequestNumber
        {
            get
            {
                return this._ServiceRequestNumberField;
            }
            set
            {
                this._ServiceRequestNumberField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> BudgetItemGroupId
        {
            get
            {
                return this._BudgetItemGroupIdField;
            }
            set
            {
                this._BudgetItemGroupIdField = value;
            }
        }
        [XmlAttribute()]
        public System.Nullable<int> BudgetItemId
        {
            get
            {
                return this._BudgetItemIdField;
            }
            set
            {
                this._BudgetItemIdField = value;
            }
        }
        [XmlAttribute()]
        public int CustomerId
        {
            get
            {
                return this._CustomerIdField;
            }
            set
            {
                this._CustomerIdField = value;
            }
        }
        [XmlAttribute()]
        public decimal TotalCost
        {
            get
            {
                return this._TotalCostField;
            }
            set
            {
                this._TotalCostField = value;
            }
        }
        [XmlAttribute()]
        public decimal TotalPrice
        {
            get
            {
                return this._TotalPriceField;
            }
            set
            {
                this._TotalPriceField = value;
            }
        }
    }
}
