//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum ServiceRequestState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Prospecting = 1,
        [XmlEnum("8")]
        InProgress = 8,
        [XmlEnum("2")]
        Qualification = 2,
        [XmlEnum("3")]
        Won = 3,
        [XmlEnum("4")]
        Lost = 4,
        [XmlEnum("5")]
        Canceled = 5,
        [XmlEnum("6")]
        Completed = 6,
        [XmlEnum("7")]
        Closed = 7,
    }
    public partial class ServiceRequest : NumberedDataItem
    {
        public const string DataItemClassName = "ServiceRequest";
        public const string TradeMarkIdProperty = "TradeMarkId";
        public const string AccountIdProperty = "AccountId";
        public const string CustomerIdProperty = "CustomerId";
        public const string VenueProviderIdProperty = "VenueProviderId";
        public const string AgentIdProperty = "AgentId";
        public const string ResponsibleContactIdProperty = "ResponsibleContactId";
        public const string ServiceRequestTypeIdProperty = "ServiceRequestTypeId";
        public const string ServiceLevelIdProperty = "ServiceLevelId";
        public const string ReasonIdProperty = "ReasonId";
        public const string LeadSourceIdProperty = "LeadSourceId";
        public const string ProjectIdProperty = "ProjectId";
        public const string AmountOfGuestsProperty = "AmountOfGuests";
        public const string ValueProperty = "Value";
        public const string MileageProperty = "Mileage";
        public const string EventLocationProperty = "EventLocation";
        public const string EventMonthProperty = "EventMonth";
        public const string EventDateProperty = "EventDate";
        public const string EventDurationProperty = "EventDuration";
        private System.Nullable<int> _TradeMarkIdField;
        private int _AccountIdField;
        private System.Nullable<int> _CustomerIdField;
        private System.Nullable<int> _VenueProviderIdField;
        private System.Nullable<int> _AgentIdField;
        private System.Nullable<int> _ResponsibleContactIdField;
        private int _ServiceRequestTypeIdField;
        private int _ServiceLevelIdField;
        private int _ReasonIdField;
        private System.Nullable<int> _LeadSourceIdField;
        private int _ProjectIdField;
        private System.Nullable<int> _AmountOfGuestsField;
        private System.Nullable<decimal> _ValueField;
        private System.Nullable<int> _MileageField;
        private string _EventLocationField;
        private System.Nullable<System.DateTime> _EventMonthField;
        private System.Nullable<System.DateTime> _EventDateField;
        private int _EventDurationField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public ServiceRequestState State
        {
            get
            {
                return (ServiceRequestState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="TradeMarkId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> TradeMarkId
        {
            get
            {
                return this._TradeMarkIdField;
            }
            set
            {
                this._TradeMarkIdField = value;
                InvokePropertyChanged("TradeMarkId");
            }
        }
        [Column(Name="AccountId", IsNullable=false)]
        [XmlAttribute()]
        public int AccountId
        {
            get
            {
                return this._AccountIdField;
            }
            set
            {
                this._AccountIdField = value;
                InvokePropertyChanged("AccountId");
            }
        }
        [Column(Name="CustomerId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> CustomerId
        {
            get
            {
                return this._CustomerIdField;
            }
            set
            {
                this._CustomerIdField = value;
                InvokePropertyChanged("CustomerId");
            }
        }
        [Column(Name="VenueProviderId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> VenueProviderId
        {
            get
            {
                return this._VenueProviderIdField;
            }
            set
            {
                this._VenueProviderIdField = value;
                InvokePropertyChanged("VenueProviderId");
            }
        }
        [Column(Name="AgentId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> AgentId
        {
            get
            {
                return this._AgentIdField;
            }
            set
            {
                this._AgentIdField = value;
                InvokePropertyChanged("AgentId");
            }
        }
        [Column(Name="ResponsibleContactId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> ResponsibleContactId
        {
            get
            {
                return this._ResponsibleContactIdField;
            }
            set
            {
                this._ResponsibleContactIdField = value;
                InvokePropertyChanged("ResponsibleContactId");
            }
        }
        [Column(Name="ServiceRequestTypeId", IsNullable=false)]
        [XmlAttribute()]
        public int ServiceRequestTypeId
        {
            get
            {
                return this._ServiceRequestTypeIdField;
            }
            set
            {
                this._ServiceRequestTypeIdField = value;
                InvokePropertyChanged("ServiceRequestTypeId");
            }
        }
        [Column(Name="ServiceLevelId", IsNullable=false)]
        [XmlAttribute()]
        public int ServiceLevelId
        {
            get
            {
                return this._ServiceLevelIdField;
            }
            set
            {
                this._ServiceLevelIdField = value;
                InvokePropertyChanged("ServiceLevelId");
            }
        }
        [Column(Name="ReasonId", IsNullable=false)]
        [XmlAttribute()]
        public int ReasonId
        {
            get
            {
                return this._ReasonIdField;
            }
            set
            {
                this._ReasonIdField = value;
                InvokePropertyChanged("ReasonId");
            }
        }
        [Column(Name="LeadSourceId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> LeadSourceId
        {
            get
            {
                return this._LeadSourceIdField;
            }
            set
            {
                this._LeadSourceIdField = value;
                InvokePropertyChanged("LeadSourceId");
            }
        }
        [Column(Name="ProjectId", IsNullable=false)]
        [XmlAttribute()]
        public int ProjectId
        {
            get
            {
                return this._ProjectIdField;
            }
            set
            {
                this._ProjectIdField = value;
                InvokePropertyChanged("ProjectId");
            }
        }
        [Column(Name="AmountOfGuests", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> AmountOfGuests
        {
            get
            {
                return this._AmountOfGuestsField;
            }
            set
            {
                this._AmountOfGuestsField = value;
                InvokePropertyChanged("AmountOfGuests");
            }
        }
        [Column(Name="Value", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<decimal> Value
        {
            get
            {
                return this._ValueField;
            }
            set
            {
                this._ValueField = value;
                InvokePropertyChanged("Value");
            }
        }
        [Column(Name="Mileage", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> Mileage
        {
            get
            {
                return this._MileageField;
            }
            set
            {
                this._MileageField = value;
                InvokePropertyChanged("Mileage");
            }
        }
        [Column(Name="EventLocation", IsNullable=true, MaximumLength=256)]
        [XmlAttribute()]
        public string EventLocation
        {
            get
            {
                return this._EventLocationField;
            }
            set
            {
                this._EventLocationField = value;
                InvokePropertyChanged("EventLocation");
            }
        }
        [Column(Name="EventMonth", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<System.DateTime> EventMonth
        {
            get
            {
                return this._EventMonthField;
            }
            set
            {
                this._EventMonthField = value;
                InvokePropertyChanged("EventMonth");
            }
        }
        [Column(Name="EventDate", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<System.DateTime> EventDate
        {
            get
            {
                return this._EventDateField;
            }
            set
            {
                this._EventDateField = value;
                InvokePropertyChanged("EventDate");
            }
        }
        [Column(Name="EventDuration", IsNullable=false)]
        [XmlAttribute()]
        public int EventDuration
        {
            get
            {
                return this._EventDurationField;
            }
            set
            {
                this._EventDurationField = value;
                InvokePropertyChanged("EventDuration");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
