//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum SizeOfServiceRequestState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
        [XmlEnum("2")]
        Inactive = 2,
    }
    public partial class SizeOfServiceRequest : DataItem
    {
        public const string DataItemClassName = "SizeOfServiceRequest";
        public const string MinimumValueProperty = "MinimumValue";
        public const string MaximumValueProperty = "MaximumValue";
        private decimal _MinimumValueField;
        private decimal _MaximumValueField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public SizeOfServiceRequestState State
        {
            get
            {
                return (SizeOfServiceRequestState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="MinimumValue", IsNullable=false)]
        [XmlAttribute()]
        public decimal MinimumValue
        {
            get
            {
                return this._MinimumValueField;
            }
            set
            {
                this._MinimumValueField = value;
                InvokePropertyChanged("MinimumValue");
            }
        }
        [Column(Name="MaximumValue", IsNullable=false)]
        [XmlAttribute()]
        public decimal MaximumValue
        {
            get
            {
                return this._MaximumValueField;
            }
            set
            {
                this._MaximumValueField = value;
                InvokePropertyChanged("MaximumValue");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
