//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum UnitOfMeasureClassState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
    }
    public partial class UnitOfMeasureClass : DataItem
    {
        public const string DataItemClassName = "UnitOfMeasureClass";
        public const string BaseUnitOfMeasureIdProperty = "BaseUnitOfMeasureId";
        private System.Nullable<int> _BaseUnitOfMeasureIdField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public UnitOfMeasureClassState State
        {
            get
            {
                return (UnitOfMeasureClassState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="BaseUnitOfMeasureId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> BaseUnitOfMeasureId
        {
            get
            {
                return this._BaseUnitOfMeasureIdField;
            }
            set
            {
                this._BaseUnitOfMeasureIdField = value;
                InvokePropertyChanged("BaseUnitOfMeasureId");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
