//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DykBits.Crm.Data
{
    using System;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    public enum UserNotificationState : byte
    {
        [XmlEnum("0")]
        NotExist = 0,
        [XmlEnum("1")]
        Active = 1,
        [XmlEnum("2")]
        Inactive = 2,
    }
    public partial class UserNotification : DataItem
    {
        public const string DataItemClassName = "UserNotification";
        public const string DocumentTypeIdProperty = "DocumentTypeId";
        public const string DocumentIdProperty = "DocumentId";
        public const string UserIdProperty = "UserId";
        private System.Nullable<int> _DocumentTypeIdField;
        private System.Nullable<int> _DocumentIdField;
        private int _UserIdField;
        public override string DataItemClass
        {
            get
            {
                return DataItemClassName;
            }
        }
        [XmlAttribute()]
        public UserNotificationState State
        {
            get
            {
                return (UserNotificationState)((IDataItem)this).State;
            }
            set
            {
                ((IDataItem)this).State = (byte)value;
            }
        }
        [Column(Name="DocumentTypeId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> DocumentTypeId
        {
            get
            {
                return this._DocumentTypeIdField;
            }
            set
            {
                this._DocumentTypeIdField = value;
                InvokePropertyChanged("DocumentTypeId");
            }
        }
        [Column(Name="DocumentId", IsNullable=true)]
        [XmlAttribute()]
        public System.Nullable<int> DocumentId
        {
            get
            {
                return this._DocumentIdField;
            }
            set
            {
                this._DocumentIdField = value;
                InvokePropertyChanged("DocumentId");
            }
        }
        [Column(Name="UserId", IsNullable=false)]
        [XmlAttribute()]
        public int UserId
        {
            get
            {
                return this._UserIdField;
            }
            set
            {
                this._UserIdField = value;
                InvokePropertyChanged("UserId");
            }
        }
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            NotifyPropertyChangedInternal(e.PropertyName);
            base.OnPropertyChanged(e);
        }

		partial void NotifyPropertyChangedInternal(string propertyName);
    }
}
