CREATE TABLE [dbo].[Product]
(
	[Id] TIdentifier not null primary key identity,
	[State] TState not null,
	[OrganizationId] TIdentifier not null default(2),
	[ProductClass] TIdentifier not null default(0),
	[Code] TCode null,
	[FileAs] TName not null,
	[FullName] nvarchar(1024) null,
	[AbstractProductId] TIdentifier null,
	[ProductTypeId] TIdentifier not null default(1),
	[ProductCategoryId] TIdentifier not null,
	[ProductSubcategoryId] TIdentifier null,
	[ServiceLevelId] TIdentifier not null default(2),
	[AllowNegativeBalance] bit not null default(0),
	[CountryId] TIdentifier null,
	[Manufacturer] nvarchar(64) null,
	[SupplierId] TIdentifier null,
	[ItemColorId] TIdentifier null,
	[ListPrice] [TMoney] NOT null default(0),
	[StandardCost] [TMoney] NOT null default(0),
	[PriceMarginId] TIdentifier not null default(1),
	[UnitOfMeasureId] TIdentifier not null,
	[Size] decimal(8,2) null,
	[SizeUnitOfMeasureId] TIdentifier null,
	[Weight] decimal(8,2) null,
	[WeightUnitOfMeasureId] TIdentifier null,
	[DiscontinuedDate] date null,
	[Picture] varbinary(max) null,
	[Comments] nvarchar(max) null, 
    [Created] datetime not null, 
    [CreatedBy] int not null, 
    [Modified] datetime not null, 
    [ModifiedBy] int not null, 
    [RowVersion] rowversion not null, 
    CONSTRAINT [FK_Product_ProductCategory] FOREIGN KEY ([ProductCategoryId]) REFERENCES [dbo].[ProductCategory]([Id]), 
    CONSTRAINT [FK_Product_ProductSubcategory] FOREIGN KEY ([ProductSubcategoryId]) REFERENCES [dbo].[ProductSubcategory]([Id]), 
    CONSTRAINT [FK_Product_UnitOfMeasure] FOREIGN KEY ([UnitOfMeasureId]) REFERENCES [dbo].[UnitOfMeasure]([Id]), 
    CONSTRAINT [FK_Product_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country]([Id]), 
    CONSTRAINT [FK_Product_ItemColor] FOREIGN KEY ([ItemColorId]) REFERENCES [dbo].[ItemColor]([Id]), 
    CONSTRAINT [FK_Product_AbstractProduct] FOREIGN KEY ([AbstractProductId]) REFERENCES [dbo].[AbstractProduct]([Id]), 
    CONSTRAINT [FK_Product_ProductType] FOREIGN KEY ([ProductTypeId]) REFERENCES [dbo].[ProductType]([Id]), 
    CONSTRAINT [FK_Product_Supplier] FOREIGN KEY ([SupplierId]) REFERENCES [dbo].[Account]([Id]), 
    CONSTRAINT [FK_Product_PriceMargin] FOREIGN KEY ([PriceMarginId]) REFERENCES [dbo].[PriceMargin]([Id])
)
